// Notas de Versão — atualizado a cada commit
const NotasVersao = {
  versaoAtual: 'V2.17.15',

  versoes: [
    {
      versao: 'V1.0',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'lancamento',
      titulo: 'Lançamento Oficial da Base',
      itens: [
        'Sistema publicado em produção (Vercel + Firebase)',
        'Identidade visual Absoluta: preto + amarelo #F5C800',
        'Logo oficial, sidebar escura, header com borda amarela',
        'Card especial obra Essence/Zenith com foto',
        'Módulo Obras: criar, listar, editar, excluir',
        'Módulo Configuração da Obra: etapas, pacotes, locais, equipes',
        'Módulo Levantamentos (hub)',
        'Módulo Levantamento de Fachada — calculadora completa',
        '  → Hierarquia: Fachada → Balancim → Vista → Peça',
        '  → m² sem ML, m² com ML, Metro Linear, Vão Fechado',
        '  → Checkbox "Pode ser ML" por peça',
        '  → 4 modos de desconto de janela configuráveis',
        '  → Vão fechado por Vista (não por peça)',
        '  → Visão Geral com mapa PNG + caixas posicionáveis',
        '  → Exportação CSV',
        'Módulo Planejamento V1: Gantt, Linha de Balanço, Escadinha, Tabela',
        'Auditoria automática em todas as operações',
      ]
    },
    {
      versao: 'V1.0.1',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'correcao',
      titulo: 'Correções de autenticação e dados',
      itens: [
        'firebase-config.js: reutiliza app existente (não chama initializeApp duas vezes)',
        'Fachada: carregar com fallback duplo (sem orderBy → com createdAt)',
        'Fachada: múltiplas fachadas abertas na árvore simultaneamente',
        'Fachada: ✎ inline para renomear fachada/balancim',
        'Fachada: Visão Geral antes do Resumo Geral',
        'Fachada: canvas branco com padding para posicionamento',
        'Fachada: card de total geral na Visão Geral',
        'Obras: editar obra existente funcionando',
        'Router: troca de obra recarrega módulo automaticamente',
        'Notas de Versão: criadas e acessíveis na sidebar',
      ]
    },
    {
      versao: 'V1.0.2',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'correcao',
      titulo: 'Correção definitiva de autenticação',
      itens: [
        'auth.js: reescrito do zero — sem timers conflitantes',
        '  → onAuthStateChanged ignora null completamente (Firebase restaurando sessão)',
        '  → Timeout único de 8s só ativa se realmente não houver sessão',
        '  → Resolve definitivamente o bug de usuário sumindo ao navegar',
        'utils.js: initPagina sem timeout próprio — usa apenas o do auth',
        '  → Erros do Firestore (seletor de obras) não bloqueiam a página',
        '  → Usuário nunca é redirecionado por erro de Firestore',
        'Versão atual visível na sidebar (ex: V1.0.2)',
        'Notas de versão bumpeadas a cada commit (V1.0.2)',
        'CRÍTICO fachada: cxVincular não existia → travava o módulo inteiro',
        '  → Corrigido para cxEditar e salvarCxEdit',
        '  → LevantamentoFachada undefined era consequência deste erro',
        'Obras: removidas imagens hardcoded (Essence/Zenith)',
        'Obras: botão Inserir Imagem no modal — cada obra tem sua própria foto',
        'Fachada: toggle Visão Geral agora abre primeiro (antes de Resumo Geral)',
        'Fachada: mapa migra dados de chave antiga (fachadaMap_null) para chave correta',
        '  → Imagem importada volta a aparecer após correção do bug anterior',
        'Mapa (Visão Geral): migrado de localStorage para Firestore',
        '  → Imagem e posições das caixas disponíveis em qualquer dispositivo',
        '  → Carregado junto com os dados da fachada no init()',
        'Layout geral: sidebar fixa em 100vh, usuário sempre visível sem scroll',
        'Visão Geral: layout compacto — topbar, total e mapa cabem na tela',
        '  → Toggle + botões na mesma linha (topbar)',
        '  → Mapa ocupa o espaço restante da tela automaticamente',
        '  → Imagem responsiva dentro da área de mapa',
        'Imagens: migradas de base64/localStorage para Firebase Storage',
        '  → Mapa da Visão Geral: upload para Storage, URL salva no Firestore',
        '  → Imagem de capa das obras: upload para Storage',
        '  → Resolve limite de 1MB do Firestore e persistência entre dispositivos',
        'Mapa: imagem no tamanho natural com scroll — não mais cortada',
        'Imagem: compressão via canvas (sem Firebase Storage) — sem loading infinito',
        '  → Reduz para <900KB antes de salvar no Firestore',
        '  → Qualidade progressiva: 85% → 30% até caber',
        'Visão Geral: sidebar esquerda oculta para maximizar área do mapa',
        '  → Aparece de volta ao entrar no Resumo Geral',
        'Visão Geral: imagem ocupa toda a largura disponível (fit)',
        'Drag das caixas: reescrito com mouse events (mousedown/mousemove/mouseup)',
        '  → Movimento preciso, sem travar, sem voltar ao lugar inicial',
        '  → Considera scroll do wrapper no cálculo de posição',
      ]
    },
    {
      versao: 'V1.0.3',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'correcao',
      titulo: 'Correções de layout e mapa',
      itens: [
        'Imagem do mapa: compressão via canvas — sem loading infinito',
        'Imagem do mapa: salva comprimida no Firestore (sem Firebase Storage)',
        'Visão Geral: sidebar esquerda oculta para maximizar área do mapa',
        'Visão Geral: imagem ocupa toda a largura disponível (fit)',
        'Drag das caixas: reescrito com mousedown/mousemove/mouseup',
        '  → Movimento preciso, não volta ao lugar inicial',
        '  → Considera scroll do wrapper no cálculo de posição',
        'Layout geral: sidebar fixa em 100vh, usuário sempre visível',
        'Versão atualizada para V1.0.3 em todos os arquivos',
      ]
    },
    {
      versao: 'V1.0.4',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'correcao',
      titulo: 'Visão Geral: sidebar, drag e imagem corrigidos',
      itens: [
        'Sidebar esquerda oculta na Visão Geral — toda a tela para o mapa',
        '  → Grade muda para 1 coluna (sem sidebar)',
        '  → Volta ao normal no Resumo Geral',
        'Drag das caixas reescrito corretamente com mouse events',
        '  → Caixas se movem livremente, não travam, não voltam ao lugar',
        '  → Offset calculado relativo ao mapa-area com scroll do wrapper',
        'Ícone de cadeado: 🔓 aberto (livre) / 🔒 fechado (travado) — visível',
        'Botões da caixa não ativam drag ao clicar (stopPropagation)',
        'Imagem ocupa 100% da largura do mapa com scroll quando maior',
        'pointer-events:none no container, pointer-events:all por caixa',
      ]
    }
    ,{
      versao: 'V1.0.5',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'correcao',
      titulo: 'Sidebar, caixas livres e imagem fit',
      itens: [
        'Sidebar da estrutura: id adicionado ao HTML — agora some de verdade na Visão Geral',
        'Caixas sem limite de posição — movem livremente para qualquer lugar',
        'Imagem do mapa: object-fit contain — cabe na tela sem scroll, sem corte',
        'Save do mapa: log de debug + validação de tamanho antes de salvar',
        '  → Mostra erro claro se imagem ainda for grande demais',
      ]
    },
    {
      versao: 'V1.0.6',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'correcao',
      titulo: 'Estrutura some + zoom do mapa',
      itens: [
        'Coluna Estrutura (fachada-tree): agora some de verdade na Visão Geral',
        '  → renderPainel() usa getElementById corretamente',
        '  → Volta ao abrir Resumo Geral',
        'Controles de zoom na Visão Geral: − / % / + / ↺ reset',
        '  → Zoom de 20% a 300% para ajustar a imagem na tela',
        '  → Caixas escalam junto com a imagem',
        'Mapa: overflow auto — scroll só quando zoom > tela',
      ]
    },
    {
      versao: 'V1.0.7',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'correcao',
      titulo: 'Canvas infinito + redimensionar imagem',
      itens: [
        'Botão ✎ Tamanho na topbar — abre slider para ajustar largura da imagem',
        '  → Slider de 200px a 3000px em tempo real',
        '  → Caixas permanecem onde estão ao redimensionar',
        'Canvas infinito (2000×1400px mínimo) com fundo pontilhado',
        '  → Caixas podem ficar em qualquer lugar, inclusive fora da imagem',
        '  → Scroll livre para navegar pelo canvas',
        'Imagem posicionada no canto superior esquerdo do canvas',
        '  → Margem de 40px ao redor para posicionar caixas fora da imagem',
      ]
    },
        {
      versao: 'V1.0.8',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'correcao',
      titulo: 'Imagem arrastável e redimensionável com handles',
      itens: [
        'Imagem do mapa: drag para mover (arrastar em qualquer direção)',
        'Imagem do mapa: 8 handles amarelos nos cantos e bordas para redimensionar',
        '  → Arrastar canto: resize proporcional',
        '  → Arrastar borda: resize direcional',
        'Imagem cabe na tela ao importar (fit automático)',
        'Canvas sem overflow/scroll — imagem e caixas sempre visíveis',
        'Borda tracejada amarela indica que a imagem é editável',
      ]
    },
    {
      versao: 'V1.0.9',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'correcao',
      titulo: 'Resize correto, fundo branco, caixas livres, cadeado legível',
      itens: [
        'Handles de resize: corrigidos — agora redimensiona a imagem corretamente',
        'Caixas: drag corrigido — posição relativa ao canvas (não à area)',
        'Fundo do canvas: branco puro (sem pontinhos)',
        'Cadeado: substituído por texto LIVRE (verde) / TRAV (vermelho)',
        '  → Muito mais legível que emoji de cadeado',
      ]
    },
    {
      versao: 'V1.1.0',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'funcionalidade',
      titulo: 'Resize completo de imagem e caixas na Visão Geral',
      itens: [
        'Imagem: 8 handles amarelos para redimensionar (4 cantos + 4 bordas)',
        '  → Cantos: resize proporcional (mantém proporção da imagem)',
        '  → Bordas E/W: estica horizontalmente',
        '  → Bordas N/S: estica verticalmente com proporção',
        'Imagem: arrastar para mover livremente no canvas',
        'Imagem: fit automático ao importar (cabe na tela)',
        'Caixas: handle ⤡ no canto inferior direito para redimensionar largura',
        '  → Conteúdo se adapta à largura da caixa',
        'Caixas: ficam sempre em cima da imagem (z-index:20 vs z-index:1)',
        'Canvas: fundo branco puro, sem pontinhos',
        'Lock: LIVRE (verde) / TRAV (vermelho) — legível',
      ]
    },
    {
      versao: 'V1.1.1',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'correcao',
      titulo: 'Visão Geral: modo edição, imgState no Firestore, resize caixas',
      itens: [
        'Imagem: botão Editar Imagem ativa modo edição (borda amarela)',
        'Imagem: botão Confirmar salva posição/tamanho no Firestore e trava',
        '  → Imagem não se move/redimensiona fora do modo edição',
        'Imagem: imgState (x,y,w) salvo no Firestore — persiste ao recarregar',
        'Caixas: resize em largura (E) e altura (S) separados',
        '  → Handle ⤡ no canto: resize em diagonal (largura+altura)',
        '  → Barra na base: resize só em altura',
        'Caixas: ficam acima da imagem (z-index:30 vs z-index:1)',
      ]
    },
    {
      versao: 'V1.1.2',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'correcao',
      titulo: 'Caixas nunca cortadas + imgState persistido',
      itens: [
        'Caixas: movidas para overlay fora do canvas (overflow:visible)',
        '  → Nunca mais cortadas — podem ir para qualquer lugar da tela',
        'imgState salvo no Firestore — posição e tamanho da imagem persistem',
        'Modo edição: botão confirmar salva e trava imagem',
        'Resize caixas: handle ⤡ para largura+altura simultâneos',
        'Texto das caixas: flex-wrap para refluir ao redimensionar',
      ]
    },
    {
      versao: 'V1.1.3',
      status: 'fechada',
      data: '2025-07-05',
      tipo: 'correcao',
      titulo: 'Auth corrigido, fórmula ML do config, vãos múltiplos',
      itens: [
        'CRÍTICO: carregar() agora carrega mapaVisao do Firestore novamente',
        '  → Imagem e caixas voltam ao abrir a página',
        '  → Usuário não buga mais ao entrar em fachada',
        'Fórmula ML: usa ml_percentual do config (não mais fixo em 50%)',
        '  → Ex: 100% → ml conta inteiro no equivalente: 6m² + 4ml = 10m²',
        '  → Ex: 50%  → ml conta metade: 6m² + 4ml = 8m²',
        'Vão Fechado por Vista: múltiplos vãos por vista',
        '  → Cada vão tem Comprimento, Altura e Quantidade',
        '  → Botão + Adicionar Vão para incluir mais vãos',
        '  → Total acumulado exibido em tempo real',
      ]
    },
    {
      versao: 'V1.1.4',
      status: 'fechada',
      data: '2025-07-05',
      tipo: 'correcao',
      titulo: 'CRÍTICO: funções perdidas restauradas',
      itens: [
        'CAUSA RAIZ do bug: reescritas da Visão Geral deletaram funções essenciais',
        '  → importarMapa, cxAdicionar, cxRemover, cxTravar, cxEditar, salvarCxEdit, limparMapa',
        '  → return{} exportava funções inexistentes → IIFE falhava → módulo undefined',
        '  → Usuário bugava porque o módulo não carregava',
        'Todas as funções restauradas e verificadas (47 exportadas, todas existem)',
        'cxTravar e cxEditar agora rerenderizam só as caixas (sem reload do painel inteiro)',
      ]
    },
    {
      versao: 'V1.1.5',
      status: 'fechada',
      data: '2025-07-05',
      tipo: 'correcao',
      titulo: 'Drag das caixas: reescrito simples e direto',
      itens: [
        'cxMouseDown: usa delta (startX/startY) em vez de getBoundingClientRect do overlay',
        '  → Não depende do overlay existir ou ter posição correta',
        '  → Move exatamente o quanto o mouse se deslocou',
        '  → Salva posição final no Firestore ao soltar',
      ]
    },
    {
      versao: 'V1.1.6',
      status: 'fechada',
      data: '2025-07-05',
      tipo: 'correcao',
      titulo: 'Drag caixas: header é a alça de arrasto',
      itens: [
        'CAUSA RAIZ do drag não funcionar:',
        '  → onmousedown estava no div pai, mas header tinha stopPropagation',
        '  → Qualquer clique passava pelo header e cancelava o evento',
        'Fix: onmousedown movido para o HEADER (barra amarela)',
        '  → Arrastar pelo header amarelo move a caixa',
        '  → Botões ainda têm stopPropagation para não arrastar ao clicar',
      ]
    },
    {
      versao: 'V1.2',
      status: 'fechada',
      data: '2025-07-05',
      tipo: 'funcionalidade',
      titulo: 'Planejamento funcional + Módulo Materiais',
      itens: [
        'PLANEJAMENTO — Importar Excel:',
        '  → Aceita .xlsx e .xls (SheetJS via CDN, sem instalação)',
        '  → Detecta colunas em PT e EN automaticamente',
        '  → Importa: Código, Nome, Tipo, Datas, Duração, %, Responsável, Etapa, Pacote, Local',
        '  → Calcula duração automaticamente se tiver datas',
        '  → Trata datas em DD/MM/YYYY, YYYY-MM-DD e serial Excel',
        'PLANEJAMENTO — Exportar Excel:',
        '  → Gera .xlsx com todas as tarefas',
        '  → Inclui aba de Instruções de importação',
        '  → Nome do arquivo inclui obra e data',
        'PLANEJAMENTO — Gantt melhorado:',
        '  → Linha Hoje em amarelo com label',
        '  → Barra executada real (início/término real)',
        '  → Zoom dia/semana/mês/trimestre/ano',
        'MATERIAIS — Novo módulo:',
        '  → Vínculo com tarefas do Planejamento',
        '  → Vínculo com Fachadas do Levantamento',
        '  → Consumo Previsto × Quantidade da tarefa = total calculado',
        '  → Detalhes da tarefa/fachada ao filtrar',
        '  → CRUD completo com tipo, fabricante, unidade',
      ]
    },
    {
      versao: 'V1.2.1',
      status: 'fechada',
      data: '2025-07-05',
      tipo: 'correcao',
      titulo: 'Correções Planejamento e Materiais',
      itens: [
        'Planejamento: Router.getObraAtiva → Router.getObra (exportar funcionando)',
        'Materiais: removido stub de desenvolvimento',
        'Materiais: modal de cadastro adicionado ao HTML',
        'Materiais: Levantamento Fachada aparece como UMA entrada agregada',
        '  → Agrupa todas as fachadas com m² total e detalhe por fachada',
        '  → Não lista cada fachada separada',
        'Materiais: layout organizado com tabela e filtros no topo',
      ]
    },
    {
      versao: 'V1.2.2',
      status: 'fechada',
      data: '2025-07-05',
      tipo: 'funcionalidade',
      titulo: 'Materiais: biblioteca + vínculos por UID',
      itens: [
        'Estrutura em duas coleções separadas:',
        '  → materiais/ = biblioteca (cada material com UID único)',
        '  → materiais_vinculos/ = vínculo materialId + tarefaId + consumo',
        'Aba Biblioteca: cadastrar materiais com nome, tipo, fabricante, referência',
        '  → Ex: Cimento CP-III Votorantim e Cimento CP-III Cauê são IDs diferentes',
        '  → Coluna mostra em quantas tarefas cada material é usado',
        'Aba Por Tarefa: vincular material da biblioteca a uma tarefa/serviço',
        '  → Busca material pelo nome na biblioteca (não digitação manual)',
        '  → Consumo Previsto × Quantidade da tarefa = total calculado',
        '  → Avisa duplicidade (mesmo material + mesma tarefa)',
        '  → Link rápido para cadastrar na biblioteca se não encontrar',
      ]
    },
    {
      versao: 'V1.2.3',
      status: 'fechada',
      data: '2025-07-05',
      tipo: 'correcao',
      titulo: 'Materiais polido + Excel sem conflito',
      itens: [
        'Excel exportar: colunas sem acentos (Inicio, Termino, Nivel, Perc Concluido)',
        '  → Importar detecta com ou sem acento, normaliza automaticamente',
        'Materiais: botão ← Por Tarefa na tela de Biblioteca',
        'Materiais: modal único Vincular / Criar com toggle no topo',
        '  → Vincular: busca na biblioteca',
        '  → Criar: formulário inline, salva na biblioteca e vincula de uma vez',
        'Unidade de consumo: sempre no formato X/Y (kg/m², L/m², un/un...)',
        '  → Consumo real herda a mesma unidade (label dinâmico)',
        '  → Dropdown com opções padrão de mercado',
        'Card de tarefa: exibe apenas total (m², un...) sem listar fachadas',
      ]
    },
    {
      versao: 'V1.2.4',
      status: 'fechada',
      data: '2025-07-05',
      tipo: 'correcao',
      titulo: 'Materiais: editar corrigido, embalagem, relatório por balancim',
      itens: [
        'Editar material na biblioteca: botão funcionando (preenchimento manual)',
        'Material com conversão de embalagem: 1 saco = 20 kg',
        '  → Total exibido em unidade base E em embalagem',
        '  → Ex: 840 kg = 42 sacos de 20 kg',
        'Relatório Fachada: ao filtrar por [Levantamento] Fachada',
        '  → Tabela por material com breakdown por Fachada e por Balancim',
        '  → Total por fachada e total geral em destaque amarelo',
        '  → Mostra total em unidade base e em embalagem se configurado',
        'HTML do modal reconstruído limpo (sem duplicação)',
        'Consumo real: label dinâmico com mesma unidade do previsto',
      ]
    },
    {
      versao: 'V1.2.5',
      status: 'fechada',
      data: '2025-07-05',
      tipo: 'correcao',
      titulo: 'Importar/Exportar Excel: formato exato do modelo',
      itens: [
        'IMPORTAR: detecta colunas do modelo real (ID, Código, Nome, Duração...)',
        '  → Colunas: ID, Código, Nome, Duração, Início, Término, % Esperado',
        '  → % Concluído, Prececessora, Tarefa Pai, Grupo, Local, Custo, Receita',
        '  → Responsável, Inicio/Termino Linha de Base, Inicio/Termino Desafio',
        '  → Duração no formato Xd (ex: 20d)',
        '  → Datas no formato DD/MM/YYYY',
        '  → Hierarquia detectada por recuo de espaços no nome',
        'IMPORTAR: gravação em lotes de 50 (sem loading infinito)',
        '  → Antes: 2399 awaits sequenciais = travava',
        '  → Agora: Promise.all em lotes = rápido',
        'EXPORTAR: cabeçalho idêntico ao modelo importável',
        '  → Nome com recuo por nível (2 espaços por nível)',
        '  → Datas em DD/MM/YYYY, duração com sufixo d',
        '  → Todas as 19 colunas do modelo',
      ]
    },
    {
      versao: 'V1.3',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'funcionalidade',
      titulo: 'Planejamento: Gantt tipo MS Project',
      itens: [
        'Hierarquia: grupos com ▼/▶ para recolher/expandir filhos',
        'Hierarquia: botões ← → na tabela para recuar/avançar nível',
        'Hierarquia: Ctrl++ nova tarefa, Ctrl+- excluir selecionada',
        'Colunas: botão ⚙ Colunas para mostrar/esconder cada coluna',
        'Divisor: barra amarela entre tabela e Gantt é arrastável',
        'Scroll sincronizado: esquerda e direita rolam juntos',
        'Importar: confirma antes de substituir, apaga antigas primeiro',
        'Exportar Gantt: botão 🖼 Gantt PDF gera imagem PNG',
        'Zoom: dia/semana/mês/trimestre/ano com escala correta',
        'Modal tarefa: todos os campos do modelo Excel',
        'Barras de grupo: formato chapéu (MS Project style)',
        'Linha de base e desafio como campos separados',
      ]
    },
    {
      versao: 'V1.3.1',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'correcao',
      titulo: 'Planejamento: performance + duplicatas + colunas',
      itens: [
        'PERFORMANCE: renderização virtual — só linhas visíveis no viewport',
        '  → 2400 tarefas sem travar (antes renderizava tudo de uma vez)',
        '  → Scroll sincronizado esquerda/direita',
        'Coluna # (número da linha) sempre visível',
        'Coluna Predecessora visível',
        'Esconder coluna: clique no ▼ no header da própria coluna',
        '  → Botão "Mostrar colunas" aparece quando alguma está oculta',
        'Import: evita duplicatas (chave código+nome)',
        '  → Limpa tudo antes de importar',
        'Inserir tarefa: herda nível/grupo da selecionada, empurra as demais',
        'Ctrl++ insere, Ctrl+- exclui selecionada',
        'Divisor amarelo arrastável entre tabela e Gantt',
      ]
    },
    {
      versao: 'V1.3.2',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'correcao',
      titulo: 'Planejamento: colunas, import, hierarquia, zoom',
      itens: [
        'Colunas: nomes completos (Duração, % Esperado, % Concluído, Predecessora)',
        'Colunas: clique DIREITO no header para esconder (menos sensível)',
        'Colunas: mostrar individual — popup lista apenas as ocultas',
        'Colunas: arrastar borda direita do header para redimensionar largura',
        'Import: removida deduplicação — todas as linhas são importadas',
        '  → Suporte a 10.000+ linhas (lotes de 200)',
        '  → Linhas com mesmo nome mas níveis diferentes são mantidas',
        'Hierarquia ← →: move a tarefa E todos os filhos abaixo dela',
        '  → Igual MS Project: outdent/indent puxa a família inteira',
        'Zoom: escala correta dia/semana/mês/trimestre/ano',
      ]
    },
    {
      versao: 'V1.3.3',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'correcao',
      titulo: 'Planejamento: ← → no Gantt, zoom correto, esconder Gantt',
      itens: [
        'Aba Tabela removida — tudo feito pelo Gantt',
        'Botões ← → de hierarquia agora no Gantt (coluna Ações)',
        '  → Recuar/avançar move tarefa + todos os filhos abaixo',
        'Botão Esconder Gantt: esconde as barras e deixa só a tabela',
        '  → Toggle: clica de novo para mostrar o Gantt',
        'Zoom headers corrigidos:',
        '  → Dia: mostra cada dia individualmente',
        '  → Semana: linhas verticais por semana com número do dia',
        '  → Mês: label por mês com ano',
        '  → Trimestre: T1/T2/T3/T4 com ano',
        '  → Ano: só o número do ano',
        'Coluna Ações alargada (64px) para caber ← → ✎',
      ]
    },
    {
      versao: 'V2.0',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'funcionalidade',
      titulo: 'Planejamento V2.0 — reescrita completa',
      itens: [
        'EDIÇÃO INLINE: clique na célula para editar direto (sem modal)',
        '  → Enter salva, Escape cancela, Tab avança',
        '  → Funciona para todos os campos editáveis',
        'COLUNA NÍVEL: mostra o nível hierárquico de cada tarefa',
        'HIERARQUIA ← →: move tarefa + todos os filhos abaixo',
        '  → Update em paralelo para performance',
        '  → Atualiza dados locais antes de recarregar',
        'COLUNAS:',
        '  → Nomes completos sem abreviação',
        '  → Clique DIREITO no header para esconder',
        '  → Mostrar: popup lista ocultas individualmente',
        '  → Arrastar borda direita do header para redimensionar',
        '  → Arrastar header para reordenar (drag and drop)',
        '  → Reorder não afeta importar/exportar Excel',
        'TOGGLE GANTT: 1 clique para esconder/mostrar',
        '  → Tabela ocupa tela toda quando Gantt oculto',
        '  → Não reaparece ao scrollar',
        'ZOOM CORRETO:',
        '  → Dia: cada dia individualmente',
        '  → Semana: linhas por semana',
        '  → Mês: label por mês',
        '  → Trimestre: T1/T2/T3/T4',
        '  → Ano: só número do ano',
        'EXPORTAR PNG: gera imagem completa do Gantt',
        '  → Expande temporariamente para capturar tudo',
        'IMPORT: sem deduplicação, lotes de 200, limpa antes',
        'PERFORMANCE: virtual scroll + requestAnimationFrame',
      ]
    },
    {
      versao: 'V2.0.1',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'correcao',
      titulo: 'Gantt corrigido, hierarquia funcional, nível por código',
      itens: [
        'Gantt: barras voltaram — linha Hoje usa getElementById (não querySelector)',
        '  → querySelector encontrava barras de grupo e corrompia o HTML',
        'Hierarquia ← →: atualiza dados LOCALMENTE primeiro (sem esperar Firestore)',
        '  → Feedback visual imediato ao clicar',
        '  → Salva no Firestore em background em lotes de 20',
        '  → Mostra erro se tarefa já está no nível mínimo (0)',
        'Nível importado pelo CÓDIGO: 1=nível 0, 1.1=nível 1, 1.1.1=nível 2',
        '  → Antes usava espaços no nome (impreciso)',
        '  → Agora conta pontos no código = nível',
      ]
    },
    {
      versao: 'V2.0.2',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'correcao',
      titulo: 'Gantt restaurado, hierarquia por nível, famílias',
      itens: [
        'GANTT BARRAS: corrigido width:440% → width:440px no painel esquerdo',
        '  → Painel esquerdo ocupava 440% da tela, empurrando Gantt pra fora',
        'FAMÍLIAS por nível: ▼/▶ funciona baseado no NÍVEL hierárquico',
        '  → Recolher grupo esconde tudo abaixo com nível maior',
        '  → Detecta filhos pela próxima tarefa na ordem ter nível maior',
        '  → Não depende mais do campo tarefaPai',
        'NÍVEL NO IMPORT: conta pontos no código (1.3.1.1 = nível 3)',
        '  → PRECISA REIMPORTAR o Excel para corrigir os níveis',
        '← → HIERARQUIA: atualiza local primeiro (resposta imediata)',
        '  → Salva no Firestore em background',
      ]
    },
    {
      versao: 'V2.0.3',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'correcao',
      titulo: 'Divisor livre, nível por spinner, datas automáticas, predecessora',
      itens: [
        'DIVISOR: arrasta de 60px até quase o final da tela (sem limite rígido)',
        'NÍVEL: spinner funciona — change event dispara save automaticamente',
        '  → Ao mudar nível, filhos são movidos junto (MS Project)',
        'DATAS AUTOMÁTICAS (3 modos):',
        '  → Início + Fim → calcula Duração',
        '  → Início + Duração → calcula Fim',
        '  → Predecessora → calcula Início e Fim',
        'PREDECESSORA tipo MS Project:',
        '  → Formato: código + tipo (ex: 3TI, 1.2II, 5TT)',
        '  → TI = Término-Início (default): começa após a predecessora',
        '  → II = Início-Início: começa junto com a predecessora',
        '  → TT = Término-Término: termina junto com a predecessora',
        '  → Defasagem: 3TI+2 = 2 dias após término da tarefa 3',
        'RESIZE COLUNAS: arrasta borda direita do header',
      ]
    },
    {
      versao: 'V2.0.4',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'correcao',
      titulo: 'Colunas resize/reorder, predecessora popup, esconder coluna',
      itens: [
        'RESIZE COLUNAS: handle visível (amarelo ao hover) na borda direita do header',
        '  → Arrasta para redimensionar, cursor muda para col-resize',
        '  → Re-renderiza ao soltar para consistência',
        'REORDENAR COLUNAS: drag and drop nos headers',
        '  → Borda amarela indica onde vai cair',
        '  → Não afeta exportar/importar Excel',
        'ESCONDER COLUNA: clique direito no header (restaurado)',
        '  → Botão + Colunas aparece quando há ocultas',
        'PREDECESSORA — duplo clique abre popup:',
        '  → Campo de código com preview da tarefa em tempo real',
        '  → Seletor TI/II/TT/IT com descrição',
        '  → Campo de defasagem em dias',
        '  → Mostra nome, datas da predecessora',
        '  → Botão Limpar para remover predecessora',
        'PREDECESSORA — clique simples: edita o código inline',
      ]
    },
    {
      versao: 'V2.0.5',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'correcao',
      titulo: 'Resize/reorder colunas corrigidos, predecessora popup, PNG intervalo',
      itens: [
        'RESIZE COLUNAS: overlay invisível durante arrasto (sem conflito com drag)',
        '  → Desativa draggable dos headers enquanto resize',
        '  → Cursor col-resize no corpo inteiro durante arrasto',
        'REORDENAR COLUNAS: drag & drop com dataTransfer',
        '  → Coluna arrastada fica translúcida',
        '  → Borda amarela no destino',
        '  → Funciona com todas as colunas não-fixas',
        'PREDECESSORA: clique abre popup direto (sem inline)',
        '  → Código azul sublinhado indica que é clicável',
        '  → Popup com preview, tipo TI/II/TT/IT, defasagem',
        'PNG: popup pede intervalo (início/fim)',
        '  → Datas pré-preenchidas com período do projeto',
        '  → Gera PNG completo no intervalo selecionado',
      ]
    },
    {
      versao: 'V2.0.6',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'correcao',
      titulo: 'Resize colunas, reordenar, predecessora, PNG corrigidos',
      itens: [
        'RESIZE COLUNAS: overlay + linha guia amarela',
        '  → Removido HTML5 drag API (conflitava com resize)',
        '  → Handle na borda direita fica amarelo ao hover',
        '  → Overlay captura mouse, linha guia mostra posição',
        'REORDENAR COLUNAS: via menu (clique direito no header)',
        '  → Opções: ◀ Mover esquerda, Mover direita ▶, ✕ Esconder',
        '  → Removido drag&drop que não funcionava',
        'PREDECESSORA: console.log adicionado para debug',
        '  → Clique abre popup com preview em tempo real',
        'PNG: scale reduzido para 1x e altura limitada a 8000px',
        '  → Evita arquivo corrompido por canvas muito grande',
      ]
    },
    {
      versao: 'V2.0.7',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'correcao',
      titulo: 'CRÍTICO: funções faltando no return corrigidas',
      itens: [
        'insertTarefa removido (alias duplicado de inserirTarefa)',
        '_hideCol adicionada como função standalone',
        '  → Estava referenciada no menu mas não definida',
        '  → IIFE falhava → módulo undefined → usuário bugava',
        'Verificação: todas as 30 funções do return confirmadas',
      ]
    },
    {
      versao: 'V2.0.8',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'correcao',
      titulo: 'Divisor independente, resize colunas, PNG confiável',
      itens: [
        'DIVISOR: tabela tem min-width fixo e overflow:hidden',
        '  → Arrastar o divisor CORTA a tabela (não encolhe colunas)',
        '  → Colunas mantêm largura original, conteúdo é clipado',
        'RESIZE COLUNAS: handle de 8px com borda amarela visível ao hover',
        '  → Posição right:-3px para facilitar o clique',
        '  → stopPropagation evita conflito com outros eventos',
        'PNG: captura a tela como está (sem expandir)',
        '  → Usa toBlob em vez de toDataURL (mais confiável)',
        '  → Scale 2x para qualidade boa',
        '  → Sem expandir container (evita canvas gigante corrompido)',
        '30/30 funções do return verificadas',
      ]
    },
    {
      versao: 'V2.0.9',
      status: 'fechada',
      data: '2025-07-07',
      tipo: 'correcao',
      titulo: 'CRÍTICO: _totalColWidth não definida quebrava o módulo',
      itens: [
        '_totalColWidth era chamada no render mas nunca foi definida',
        '  → ReferenceError quebrava todo o Planejamento',
        'Função adicionada: soma larguras das colunas visíveis',
        'Verificação ampliada: return{} + TODAS as funções chamadas no código',
        '  → 30 funções do return OK, 29 funções internas OK',
      ]
    },
    {
      versao: 'V2.1.0',
      status: 'fechada',
      data: '2025-07-07',
      tipo: 'funcionalidade',
      titulo: 'Módulo Relatórios: "Relatórios de Vista" com IA',
      itens: [
        'Novo módulo Relatórios implementado (antes stub)',
        'Importa PDF de nota (Samsung Notes, digitada ou manuscrita)',
        '  → Nova Vercel Function api/gerar-relatorio.js chama a IA (Claude)',
        '  → Lê o PDF diretamente (sem OCR separado) e devolve JSON estruturado',
        '  → Chave de API fica só no servidor (ANTHROPIC_API_KEY no Vercel)',
        'Relatório salvo no Firestore: obras/{obraId}/relatorios',
        'PDF original arquivado no Firebase Storage',
        'Tela "Relatórios de Vista": lista os últimos relatórios em cards',
        'Visualização formatada: título, resumo, seções, pendências',
        'Botão Baixar: gera novo PDF formatado (jsPDF) e também arquiva no Storage',
        'Botão Compartilhar: abre WhatsApp com texto + link do PDF gerado',
        'Botão Excluir: remove do Firestore e do Storage (original + gerado)',
        '10/10 funções do return OK, 8/8 funções internas OK',
      ]
    },
    {
      versao: 'V2.1.1',
      status: 'fechada',
      data: '2025-07-07',
      tipo: 'correcao',
      titulo: 'Relatórios: troca de provedor de IA para API gratuita',
      itens: [
        'api/gerar-relatorio.js migrada de Anthropic (paga) para Google Gemini',
        '  → Camada gratuita da API (sem custo dentro da cota de uso)',
        '  → Variável de ambiente agora é GEMINI_API_KEY (não usa mais ANTHROPIC_API_KEY)',
        '  → Chave gerada sem cartão em aistudio.google.com/apikey',
        'Modelo usado: gemini-2.5-flash, com responseMimeType JSON nativo',
        'Testado manualmente no AI Studio com nota real — aprovado',
        'Layout do PDF de saída (jsPDF) validado com conteúdo real gerado pela IA',
      ]
    },
    {
      versao: 'V2.1.2',
      status: 'fechada',
      data: '2025-07-07',
      tipo: 'correcao',
      titulo: 'CRÍTICO: relatorios.html não chamava Relatorios.init()',
      itens: [
        'relatorios.html chamava Utils.initPagina() direto no DOMContentLoaded',
        '  → Relatorios.init() nunca era executado',
        '  → Tela ficava travada no placeholder estático "Módulo em desenvolvimento"',
        'Corrigido para chamar Relatorios.init(), igual aos demais módulos',
      ]
    },
    {
      versao: 'V2.1.3',
      status: 'fechada',
      data: '2025-07-07',
      tipo: 'funcionalidade',
      titulo: 'Relatórios: fallback automático Gemini → Claude',
      itens: [
        'api/gerar-relatorio.js agora tenta Gemini primeiro (gratuito)',
        '  → Se falhar (erro, timeout, JSON inválido, bug de billing do Google), cai automaticamente para Anthropic (pago, estável)',
        '  → Precisa de GEMINI_API_KEY e ANTHROPIC_API_KEY configuradas no Vercel',
        'Timeout de 25s (Gemini) e 30s (Anthropic) via AbortController',
        'maxDuration da function ampliado para 60s (tenta os dois provedores em sequência se necessário)',
        'Resposta da API agora inclui "provedor" usado (gemini ou anthropic)',
        'relatorios.js: exibe aviso ao usuário quando o fallback pago é usado',
      ]
    },
    {
      versao: 'V2.1.4',
      status: 'fechada',
      data: '2025-07-07',
      tipo: 'correcao',
      titulo: 'Relatórios: link de compartilhar força download do PDF',
      itens: [
        'PDF gerado agora sobe ao Storage com Content-Disposition: attachment',
        '  → Ao abrir o link no WhatsApp, o PDF baixa em vez de só abrir em visualização inline',
        'Mensagem do WhatsApp deixa explícito "📥 Baixar relatório (PDF)" antes do link',
        'Nome do arquivo padronizado (mesmo nome usado no botão Baixar)',
      ]
    },
    {
      versao: 'V2.1.5',
      status: 'fechada',
      data: '2025-07-07',
      tipo: 'funcionalidade',
      titulo: 'Relatórios: compartilhar envia o PDF anexado de verdade (no celular)',
      itens: [
        'compartilharWhatsapp agora tenta Web Share API (navigator.share) com o PDF como File',
        '  → No celular, abre o menu nativo de compartilhar com o arquivo já anexado',
        '  → Escolhendo WhatsApp, o PDF vai anexado de verdade, não como link',
        'Cancelamento do usuário no menu nativo (AbortError) não gera erro/toast',
        'Fallback mantido: desktop ou navegador sem suporte usa o link via wa.me como antes',
        'PDF sempre salvo no Storage independente do método (link de backup)',
      ]
    },
    {
      versao: 'V2.1.6',
      status: 'fechada',
      data: '2025-07-07',
      tipo: 'correcao',
      titulo: 'Relatórios: nome do arquivo baixado/compartilhado padronizado',
      itens: [
        'Formato: "Nome da Obra - Planejamento e Andamento - Data do relatório.pdf"',
        '  → Ex: "Residencial Essence - Planejamento e Andamento - 17-07-2025.pdf"',
        'Usa a data extraída pela IA (dataRelatorio) quando disponível, senão a data de criação',
        'Sanitização de caracteres inválidos em nome de arquivo (\\ / : * ? " < > |)',
        'Mesmo nome usado no botão Baixar, no Compartilhar (share nativo) e no fallback de link',
      ]
    },
    {
      versao: 'V2.2.0',
      status: 'fechada',
      data: '2025-07-07',
      tipo: 'funcionalidade',
      titulo: 'Relatórios: compartilhamento direto do Samsung Notes (PWA) + aba Pendentes',
      itens: [
        'ATENÇÃO: Relatórios migraram de subcoleção por obra (obras/{obraId}/relatorios)',
        '  para coleção raiz "relatorios" com campo obraId — relatórios de teste antigos',
        '  criados antes desta versão não aparecem mais (não foram migrados)',
        'database.js: novos helpers genéricos para coleções de nível raiz',
        '  (listarRaiz, obterRaiz, criarRaiz, atualizarRaiz, deletarRaiz, queryRaiz, novoIdRaiz)',
        'manifest.json novo: site agora é instalável como PWA, com share_target',
        '  → aceita receber arquivo PDF compartilhado por outros apps (Samsung Notes)',
        'service-worker.js novo: intercepta o POST do compartilhamento, guarda o PDF',
        '  temporariamente no IndexedDB e redireciona para share-target.html',
        'share-target.html + js/share-target.js novos: recebem o PDF, chamam a IA',
        '  (mesmo endpoint /api/gerar-relatorio) e salvam como relatório PENDENTE (obraId: null)',
        'vercel.json novo: rewrite de /share-target/ para /share-target.html',
        'Ícones do PWA gerados a partir do logo existente (icons/icon-192.png, icon-512.png)',
        'utils.js: registra manifest + service worker automaticamente em toda página autenticada',
        'relatorios.js: nova estrutura com abas "Desta Obra" e "Pendentes"',
        '  → Pendentes lista relatórios sem obraId, com dropdown pra atribuir à obra certa',
        '  → Ao atribuir, só atualiza o campo obraId (arquivo já processado, sem reprocessar)',
        'relatorios.html?aba=pendentes abre direto na aba Pendentes (usado pelo botão pós-compartilhamento)',
        '12/12 funções do return OK (relatorios.js), verificado manualmente (comentários no',
        '  return{} do database.js geraram falso positivo no script automático de checagem)',
      ]
    },
    {
      versao: 'V2.2.1',
      status: 'fechada',
      data: '2026-07-07',
      tipo: 'correcao',
      titulo: 'CRÍTICO: drag travado (Pointer Capture) — Planejamento e Fachada',
      itens: [
        'CAUSA RAIZ identificada: arrastar (resize de coluna, divisor, caixas',
        '  da Visão Geral, mover/redimensionar imagem) usava mousemove/mouseup',
        '  no document. Se o botão do mouse era solto FORA da janela do',
        '  navegador (comum com trackpad/monitor externo), o evento de',
        '  soltura nunca chegava — o listener ficava "vivo" para sempre,',
        '  reagindo a qualquer movimento de mouse na página depois.',
        '  Isso explica: caixas da fachada "enlouquecendo", imagem travada',
        '  sem conseguir confirmar posição, e o Planejamento parecendo',
        '  travar/sumir (um overlay invisível de tela cheia ficava preso',
        '  bloqueando cliques em tudo, inclusive a barra lateral).',
        '',
        'CORREÇÃO: todos os arrastos agora usam Pointer Capture',
        '  (setPointerCapture/releasePointerCapture), que garante que o',
        '  evento de soltura SEMPRE chega ao elemento correto, não importa',
        '  onde o mouse for solto. Aplicado em:',
        '  → Planejamento: resize de coluna, divisor tabela/Gantt',
        '  → Fachada: arrastar caixa, redimensionar caixa, arrastar imagem,',
        '    redimensionar imagem',
        'Removido overlay de tela cheia do resize de coluna (não é mais',
        '  necessário — Pointer Capture dispensa essa técnica)',
        'Botões dentro do header das caixas (Travar/Editar/Remover) agora',
        '  bloqueiam a propagação corretamente (estavam usando mousedown',
        '  enquanto o arrasto passou a escutar pointerdown — clique neles',
        '  também iniciava um arrasto por engano)',
      ]
    },
    {
      versao: 'V2.2.2',
      status: 'fechada',
      data: '2026-07-07',
      tipo: 'correcao',
      titulo: 'CRÍTICO: Service Worker com escopo raiz travava troca de módulo',
      itens: [
        'CAUSA RAIZ: o service worker do compartilhamento (Samsung Notes)',
        '  era registrado com escopo raiz ("/"), passando a controlar TODA',
        '  a navegação do site — literalmente toda troca de módulo (cada',
        '  link da sidebar) passava a ser interceptada por ele.',
        '',
        'CORREÇÃO: service worker agora registrado com escopo restrito a',
        '  /share-target/ (única rota que ele realmente precisa controlar,',
        '  usada pelo compartilhamento do Android). A navegação normal',
        '  entre módulos deixa de passar por ele.',
        '',
        'LIMPEZA AUTOMÁTICA: navegadores que já tinham o service worker',
        '  antigo (escopo raiz) registrado de antes desta correção têm',
        '  esse registro antigo removido automaticamente no próximo',
        '  carregamento de qualquer página — não precisa limpar cache',
        '  manualmente.',
      ]
    },
    {
      versao: 'V2.2.8',
      status: 'fechada',
      data: '2026-07-07',
      tipo: 'correcao',
      titulo: 'PNG do Gantt: renderiza o Gantt completo no intervalo, não mais print da tela',
      itens: [
        'CORRIGIDO: o botão PNG estava tirando um "print" da área visível',
        '  na tela (html2canvas na viewport atual) — o intervalo de datas',
        '  escolhido no popup nem era usado no cálculo.',
        '',
        'NOVO COMPORTAMENTO: monta um Gantt completo à parte (fora da',
        '  tela, sem paginação/scroll virtual) com TODAS as tarefas',
        '  visíveis (respeitando famílias recolhidas), com a linha do',
        '  tempo cortada exatamente no intervalo início/fim solicitado.',
        '  Só depois disso tira o PNG — do Gantt inteiro, não da tela.',
        'Barras fora do intervalo não aparecem; barras que cruzam a',
        '  borda do intervalo aparecem cortadas corretamente.',
        'Nome do arquivo agora inclui o intervalo: gantt_INICIO_a_FIM.png',
        'Proteção: avisa e cancela se o intervalo + zoom gerariam uma',
        '  imagem grande demais (reduzir período ou usar zoom Mês/Trimestre).',
      ]
    },
    {
      versao: 'V2.2.9',
      status: 'fechada',
      data: '2026-07-07',
      tipo: 'correcao',
      titulo: 'CRÍTICO: PNG do Gantt sempre pedia intervalo mesmo já selecionado',
      itens: [
        'CAUSA: o popup de datas era removido do DOM ANTES de ler os',
        '  valores dos campos início/fim. Como os campos são filhos do',
        '  popup, remover primeiro apaga os valores — a leitura seguinte',
        '  sempre retornava vazio, disparando "Selecione o intervalo"',
        '  mesmo com as datas corretamente preenchidas na tela.',
        'CORREÇÃO: os valores agora são lidos ANTES de remover o popup.',
      ]
    },
    {
      versao: 'V2.3.0',
      status: 'fechada',
      data: '2026-07-07',
      tipo: 'correcao',
      titulo: 'PNG do Gantt: escala automática — agora exporta anos inteiros sem travar',
      itens: [
        'CAUSA: a largura da imagem usava o zoom atual DA TELA (ex: Dia,',
        '  32px/dia). Pedir 3 anos nesse zoom geraria ~35.000px de',
        '  largura — daí o aviso de "intervalo grande demais".',
        '',
        'CORREÇÃO: a escala do PNG agora é escolhida automaticamente pelo',
        '  TAMANHO DO INTERVALO pedido, independente do zoom da tela:',
        '  → até 60 dias: zoom Dia',
        '  → até 240 dias: zoom Semana',
        '  → até 900 dias: zoom Mês',
        '  → até ~7 anos (2500 dias): zoom Trimestre',
        '  → períodos maiores: zoom Ano',
        '3 anos agora gera ~1300px de largura (zoom Trimestre) — rápido',
        '  e sem travar.',
        'Escala de captura (nitidez) também se ajusta automaticamente:',
        '  usa alta resolução quando cabe, reduz sozinha se a lista de',
        '  tarefas visíveis for muito grande.',
        'Aviso de erro agora diz o motivo real quando algo não cabe',
        '  (muitas tarefas visíveis vs período extenso), com sugestão',
        '  do que fazer em cada caso.',
        'Popup avisa que a escala da imagem é automática.',
      ]
    },
    {
      versao: 'V2.3.1',
      status: 'fechada',
      data: '2026-07-07',
      tipo: 'funcionalidade',
      titulo: 'PNG do Gantt: paginação automática — captura TODAS as linhas (2500+)',
      itens: [
        'PROBLEMA: uma imagem só com 2500 tarefas ficaria altíssima',
        '  (~75.000px), acima do que qualquer navegador aguenta — travava',
        '  ou corrompia o arquivo.',
        '',
        'SOLUÇÃO: paginação automática. Se as tarefas não couberem numa',
        '  imagem só (limite seguro de altura), o sistema gera VÁRIAS',
        '  imagens em sequência — cada uma com o mesmo cabeçalho de',
        '  colunas e o mesmo período de datas, cobrindo um bloco de',
        '  linhas por vez, até cobrir TODAS as tarefas.',
        '  → Ex: 2500 tarefas → 10 páginas de ~266 linhas cada',
        '  → Cada arquivo nomeado: gantt_INICIO_a_FIM_pagina_01_de_10.png',
        '  → Cada página numerada no canto (Página X de Y — linhas A–B)',
        'Toast de progresso mostra qual página está sendo gerada',
        'Pequena pausa entre downloads para o navegador não bloquear',
        '  múltiplos arquivos automáticos de uma vez',
        'Casos pequenos (cabem numa imagem só) continuam gerando um',
        '  único arquivo, sem sufixo de página — sem mudança de',
        '  comportamento pro caso comum',
      ]
    },
    {
      versao: 'V2.4.0',
      status: 'fechada',
      data: '2026-07-07',
      tipo: 'funcionalidade',
      titulo: 'Novo módulo: Levantamento de Ar Condicionado / Hidráulica',
      itens: [
        'Novo módulo dentro de Levantamentos: Ar Condicionado / Hidráulica',
        'Estrutura de Áreas configurável e editável (adicionar, renomear,',
        '  excluir área e subárea/local) — começa com "Área Comum" e',
        '  "Torre (Apartamentos)", mas totalmente livre para o usuário',
        '  reorganizar (ex: subdividir Área Comum por pavimento/local)',
        'Adicionar item ao levantamento tem 2 modos:',
        '  → Buscar da biblioteca: busca por nome com tolerância a',
        '    erro de digitação, filtrando materiais tipo "Ar',
        '    Condicionado" ou "Hidráulica"',
        '  → Criar novo material: cria direto na biblioteca de',
        '    Materiais e já usa no levantamento na mesma operação',
        'Novos tipos "Ar Condicionado" e "Hidráulica" adicionados à',
        '  biblioteca de Materiais (cadastro e criação rápida)',
        'Visão Geral consolida o total por material somando todas as',
        '  áreas — base para futura vinculação com tarefas do',
        '  Planejamento (cálculo de valor/consumo por dia no cronograma)',
      ]
    },
    {
      versao: 'V2.4.1',
      status: 'fechada',
      data: '2026-07-07',
      tipo: 'correcao',
      titulo: 'Levantamento de Ar Condicionado: busca de material mais clara',
      itens: [
        'Campo "Buscar da biblioteca" ganha foco automático ao abrir o',
        '  modal e ao trocar de aba',
        'Nome do material destaca (highlight) o trecho que bateu com o',
        '  termo buscado, deixando visível a aproximação por nome',
      ]
    },
    {
      versao: 'V2.5.0',
      status: 'fechada',
      data: '2026-07-07',
      tipo: 'funcionalidade',
      titulo: 'Módulos Semanal/Diário e Medições implementados',
      itens: [
        'SEMANAL/DIÁRIO — módulo completo, alimentado pelo Planejamento:',
        '  Modos Semana (dom-sáb) e Dia, com navegação ‹ › e botão "hoje"',
        '  Mostra tarefas planejadas para o período + atrasadas (término',
        '  vencido e % < 100), com status Atual/Atrasada/Adicionada/Omitida',
        '  Colunas: Início, Término, Esperado (calculado pela data),',
        '  Progresso, Local, Grupo, Início/Término Real, Responsável e',
        '  grade de dias com marcação amarela dos dias planejados',
        '  Lançar Progresso grava no % Concluído do Planejamento e',
        '  atualiza Início Real (1º avanço) e Término Real (100%)',
        '  Início planejado editável apenas para tarefa não iniciada',
        '  (recalcula o término pela duração)',
        '  Adicionar tarefas externas ao período (modal com árvore + busca)',
        '  Omitir tarefas com motivo obrigatório (15 opções) + detalhamento;',
        '  vista Omitidas com restauração',
        '  Seleção múltipla: barra flutuante com Datas, Responsável e Omitir',
        '  Iniciar período (baseline do avanço) e Fechar relatório:',
        '  tarefas abaixo do esperado exigem justificativa (motivo ou',
        '  observação); relatório salvo com % do período real/esperado,',
        '  % total atual/esperado da obra e PPC',
        '  Dashboard com cards do período e histórico de fechamentos',
        'MEDIÇÕES — módulo funcional:',
        '  Nova Medição: árvore completa do cronograma com recolher/expandir,',
        '  Esperado/Real por grupo (média ponderada por duração) e por tarefa',
        '  Modal de lançamento: progresso (−/＋/＝100), Início/Fim Real e',
        '  fotos (comprimidas e enviadas ao Storage)',
        '  Chips de % Total, % Medição (avanço da sessão) e % Esperado hoje',
        '  Salvar grava os % no Planejamento e registra a sessão em',
        '  obras/{id}/medicoes; lista de medições com detalhes e exclusão',
        'Novos campos nas tarefas: inicioReal e terminoReal',
      ]
    },
    {
      versao: 'V2.5.1',
      status: 'fechada',
      data: '2026-07-08',
      tipo: 'correcao',
      titulo: 'Semanal: robustez no fechamento de relatório',
      itens: [
        'Correção de erro potencial ao destacar tarefa sem justificativa',
        '  no modal de fechamento (proteção para navegadores/WebViews',
        '  sem suporte a scrollIntoView)',
        'Módulos Semanal e Medições validados com bateria de 124 testes',
        '  funcionais automatizados simulando o uso real (lançamentos,',
        '  omissões, adições, fechamentos, medições e casos extremos)',
      ]
    },
    {
      versao: 'V2.6.0',
      status: 'fechada',
      data: '2026-07-08',
      tipo: 'funcionalidade',
      titulo: 'Novo módulo: Mão de Obra (Custos)',
      itens: [
        'Novo módulo Mão de Obra dentro da seção Custos',
        'Biblioteca de mão de obra: nome e categoria (Pedreiro, Servente,',
        '  Empreiteira, etc.), reutilizável entre tarefas',
        'Vínculo por tarefa: valor unitário + unidade do valor (m², m, un,',
        '  vb, h, diária, mês) vinculado a uma tarefa do Planejamento',
        'Cálculo automático do custo total (valor unitário × quantidade',
        '  da tarefa), exibido por vínculo e como total geral/por serviço',
        'Modo "Vincular / Criar nova" no mesmo modal, igual ao módulo',
        '  Materiais, para agilizar o cadastro',
        'Adicionado ao menu de permissões (admin com acesso total,',
        '  usuário padrão sem acesso por padrão)',
      ]
    },
    {
      versao: 'V2.7.0',
      status: 'fechada',
      data: '2026-07-08',
      tipo: 'funcionalidade',
      titulo: 'Seletor hierárquico de tarefas + Custo Material/Mão de Obra no Planejamento',
      itens: [
        'SELETOR HIERÁRQUICO (Materiais e Mão de Obra):',
        '  → Antes só apareciam tarefas-folha (grupos ficavam de fora)',
        '  → Agora aparece TODA a hierarquia, com indentação por nível',
        '  → Permite vincular material/mão de obra a um nível maior',
        '    (grupo) ou a um nível menor (tarefa específica)',
        '  → Helper compartilhado: Utils.opcoesTarefaHierarquia()',
        '',
        'PREÇO DO MATERIAL (Materiais):',
        '  → Novo campo "Preço unitário (R$)" na biblioteca',
        '  → Nova coluna "Custo (R$)" na tabela Por Tarefa',
        '  → Total geral de custo em materiais exibido no topo',
        '',
        'PLANEJAMENTO — 2 colunas novas:',
        '  → "Custo Material" e "Custo M.Obra", alimentadas',
        '    automaticamente pelos módulos Materiais e Mão de Obra',
        '',
        'REGRA DE DISTRIBUIÇÃO HIERÁRQUICA:',
        '  → Custo vinculado a uma tarefa de nível N é dividido IGUALMENTE',
        '    entre os filhos diretos (nível N+1)',
        '  → Cada filho redistribui a própria parte + o que já tinha entre',
        '    os SEUS filhos, e assim por diante até as folhas',
        '  → O valor exibido em qualquer tarefa = soma de tudo que está',
        '    abaixo dela (uma tarefa-folha soma o que herdou + o que foi',
        '    vinculado direto nela; um grupo soma todos os filhos)',
        '  → Testado com 3 cenários (custo só no pai / pai+filho / só',
        '    folhas) — todos batem com a regra descrita',
      ]
    },
    {
      versao: 'V2.7.1',
      status: 'fechada',
      data: '2026-07-08',
      tipo: 'correcao',
      titulo: 'Tabela do Planejamento: scroll horizontal com arrasto',
      itens: [
        'Com as novas colunas de custo, a tabela ficou mais larga que a',
        '  área visível — antes não tinha como ver as colunas escondidas',
        '  sem arrastar o divisor até o fim',
        'Agora dá pra rolar a tabela na horizontal: barra de rolagem',
        '  normal OU clique e arraste o conteúdo pro lado (como um mapa)',
        'Cabeçalho das colunas acompanha o scroll horizontal da tabela',
        'Gantt (lado direito) continua fixo, sem ser afetado',
        'Arrastar não dispara seleção/edição de célula por engano',
      ]
    },
    {
      versao: 'V2.7.2',
      status: 'fechada',
      data: '2026-07-08',
      tipo: 'correcao',
      titulo: 'CRÍTICO: scroll horizontal da tabela sequestrava TODOS os cliques',
      itens: [
        'CAUSA: o scroll-com-arrasto (V2.7.1) capturava o ponteiro',
        '  (setPointerCapture) logo no clique, antes de confirmar que',
        '  era um arrasto de verdade. Isso sequestrava o clique de TUDO',
        '  dentro da tabela: toggle ▼/▶ de famílias, edição de célula,',
        '  botões ← → ✕ — nada respondia mais.',
        'CORREÇÃO: a captura do ponteiro só acontece DEPOIS de confirmar',
        '  movimento real (>4px). Um clique parado nunca ativa a',
        '  captura, então não interfere em nada — toggle, edição e',
        '  botões voltam a funcionar normalmente, e o arrasto horizontal',
        '  continua funcionando quando o movimento é intencional.',
      ]
    },
    {
      versao: 'V2.8.0',
      status: 'fechada',
      data: '2026-07-08',
      tipo: 'funcionalidade',
      titulo: 'Materiais: busca inteligente para vincular material à tarefa',
      itens: [
        'Vínculo de material à tarefa: os antigos menus <select> de',
        '  "Material" e "Serviço/Tarefa" foram substituídos por campos',
        '  de busca com resultado mais próximo (fuzzy, tolera erro de',
        '  digitação), igual ao padrão já usado no Levantamento de Ar',
        '  Condicionado.',
        'Busca de tarefa mantém a hierarquia do Planejamento: Nível 1,',
        '  depois seus Níveis 2, e assim por diante — permite vincular',
        '  material tanto numa tarefa-mãe quanto numa tarefa-filha.',
        'Modo "+ Criar novo material": ao digitar o nome, o sistema',
        '  mostra materiais parecidos já cadastrados na biblioteca',
        '  (mesma busca fuzzy) para evitar duplicidade — um clique usa',
        '  o material existente em vez de criar outro.',
        'Custo unitário do material (campo já existente na Biblioteca)',
        '  continua gerando automaticamente o custo total de cada',
        '  vínculo material↔tarefa, exibido na aba "Por Tarefa".',
      ]
    },
    {
      versao: 'V2.8.1',
      status: 'fechada',
      data: '2026-07-08',
      tipo: 'funcionalidade',
      titulo: 'Mão de Obra: busca hierárquica para vincular tarefa',
      itens: [
        'Vínculo de mão de obra à tarefa: o antigo <select> de',
        '  "Serviço/Tarefa" foi substituído por busca com resultado mais',
        '  próximo do que é digitado (fuzzy, tolera erro de digitação),',
        '  no mesmo padrão adotado em Materiais.',
        'Busca mantém a hierarquia do Planejamento: Nível 1, depois seus',
        '  Níveis 2, e assim por diante — permite vincular mão de obra',
        '  tanto a um nível maior (grupo/etapa) quanto a um nível menor',
        '  (tarefa folha).',
        'Válido tanto para vincular uma mão de obra já existente na',
        '  biblioteca quanto para criar uma nova na hora.',
        'Reaproveita o helper compartilhado Utils.opcoesTarefaHierarquia,',
        '  mesmo já usado no módulo Materiais, para manter os dois',
        '  módulos consistentes.',
      ]
    },
    {
      versao: 'V2.8.2',
      status: 'fechada',
      data: '2026-07-08',
      tipo: 'funcionalidade',
      titulo: 'Planejamento: reordenar linha por arrasto + cor por nível',
      itens: [
        'REORDENAR POR ARRASTO: Ctrl + botão direito + arrastar move a',
        '  tarefa (e os filhos diretos dela, se houver) pra cima ou pra',
        '  baixo na lista, encaixando antes/depois de onde soltar',
        '  → Resolve o problema de vincular um nível 4 ao nível 3 errado',
        '    quando há vários grupos do mesmo nível em sequência',
        '  → Linha some parcialmente (fica translúcida) durante o arrasto',
        '  → Barra amarela indica onde vai encaixar (antes/depois da linha)',
        '  → Local-first: tela atualiza na hora, salva no Firestore atrás',
        '',
        'COR POR NÍVEL: badge colorido na coluna Nível (cores diferentes',
        '  por nível, cíclico), ajuda a identificar rapidamente a que',
        '  grupo uma tarefa pertence mesmo com vários níveis iguais',
        '  em sequência',
        'Indentação da coluna Tarefa aumentada (14px → 20px por nível)',
        '  + linha guia vertical sutil marcando a profundidade',
      ]
    },
    {
      versao: 'V2.8.3',
      status: 'fechada',
      data: '2026-07-08',
      tipo: 'funcionalidade',
      titulo: 'Mão de Obra: exportar planilha com nome da obra em destaque',
      itens: [
        'Novo botão "📤 Exportar" no módulo Mão de Obra, gera arquivo',
        '  .xlsx (mesma biblioteca já usada em Planejamento)',
        'Nome da obra em letra grande, mesclado no topo da planilha,',
        '  antes da tabela em si — seguido de um subtítulo com a aba',
        '  exportada (Biblioteca ou Por Tarefa) e a data da exportação',
        'Aba "Por Tarefa": exporta Mão de Obra, Categoria, Serviço/Tarefa,',
        '  Valor Unit., Unidade, Quantidade da Tarefa e Custo Total, com',
        '  linha de TOTAL GERAL ao final (respeita o filtro de tarefa',
        '  ativo, se houver)',
        'Aba "Biblioteca": exporta Mão de Obra, Categoria, Observações',
        '  e número de vínculos de cada uma',
      ]
    },
    {
      versao: 'V2.9.0',
      status: 'fechada',
      data: '2026-07-09',
      tipo: 'funcionalidade',
      titulo: 'Seleção múltipla com barra de ações + coluna de status com filtro',
      itens: [
        'COLUNA DE STATUS (bolinha colorida) — 5 estados:',
        '  → Atrasado (vermelho), Alerta (laranja, vence em até 7 dias),',
        '    Em Andamento (amarelo), Em Dia (azul), Concluído (verde)',
        '  → Ícone ▼ no cabeçalho abre popup para filtrar por status',
        '  → Cores das barras do Gantt atualizadas para bater com o status',
        '',
        'SELEÇÃO MÚLTIPLA (checkbox):',
        '  → Nova coluna de checkbox na tabela',
        '  → Ao marcar 1+ tarefas, aparece barra flutuante no rodapé',
        '  → Ações em massa: ← Recuar nível, → Avançar nível,',
        '    ⧉ Duplicar, ✕ Excluir — aplicadas a todas as selecionadas',
        '  → Recuar/Avançar em massa muda só as tarefas marcadas',
        '    (não arrasta filhos junto, diferente do botão individual —',
        '    aqui você escolhe exatamente quais linhas quer mudar)',
        '',
        'CORREÇÃO: reordenar coluna por arrastar (HTML5 drag) estava',
        '  quebrada — referenciava funções que não existiam mais',
        '  (_colDragStart/_colDrop). Substituída pelo menu de clique',
        '  direito que já funcionava (mover esquerda/direita/esconder).',
      ]
    },
    {
      versao: 'V2.10.0',
      status: 'fechada',
      data: '2026-07-09',
      tipo: 'funcionalidade',
      titulo: 'Semanal: nova aba Diário — lançamento rápido de campo + relatório do dia',
      itens: [
        'NOVA ABA "DIÁRIO" no módulo Semanal — pensada pra ser rápida',
        '  no dia a dia da obra:',
        '  → Busca de tarefa por código ou nome (fuzzy, tolerante a erro',
        '    de digitação, hierárquica — mesmo padrão de Materiais/MO)',
        '  → Campo "o que está sendo feito" + 3 situações:',
        '    ✅ Executado · ◐ Parcial · ✖ Não executado',
        '  → Parcial/Não executado pedem o motivo (mesma lista de',
        '    motivos do fechamento semanal) + detalhe opcional',
        '  → Após lançar, o formulário limpa e volta o foco pra busca —',
        '    lançamentos em sequência sem pegar no mouse',
        '  → Lançamentos do dia listados por situação, com editar/excluir',
        '  → Navegação por dia (‹ › · hoje · seletor de data)',
        '',
        'RELATÓRIO DO DIA (botão 📄):',
        '  → ✅ Executado / ◐ Parcial / ✖ Não executado (com motivos)',
        '  → ⚠️ Deveria estar em execução: tarefas previstas no',
        '    Planejamento para o dia (início ≤ dia ≤ término, não',
        '    concluídas) que NÃO receberam nenhum lançamento',
        '  → 📋 Porquês do dia: todos os motivos registrados, agregados',
        '  → Botão imprimir (janela própria, pronta pra PDF)',
        '',
        'TESTE INTERNO COMPLETO (todos os módulos): sintaxe 28/28,',
        '  return{} de 20 módulos, handlers onclick 100% resolvidos,',
        '  versão consistente nos 19 HTMLs, coleções Firestore conferidas.',
      ]
    },
    {
      versao: 'V2.11.0',
      status: 'fechada',
      data: '2026-07-09',
      tipo: 'funcionalidade',
      titulo: 'Diário de Obra vira módulo próprio (Gestão) + lançamento de % no Planejamento',
      itens: [
        'DIÁRIO SAIU DO SEMANAL: agora é um módulo independente na',
        '  seção Gestão da barra lateral (📓 Diário) — o Semanal voltou',
        '  a ter só Dashboard e Tarefas, como antes',
        '',
        'NOVO: campo "Avanço %" no lançamento (opcional):',
        '  → Mostra o % atual da tarefa selecionada ao lado do nome',
        '  → O % informado é gravado DIRETO no Planejamento',
        '    (percentualConcluido), com as mesmas regras do Semanal:',
        '    primeiro avanço marca Início Real, 100% marca Término Real,',
        '    voltar de 100% limpa o Término Real',
        '  → O lançamento guarda o antes/depois (ex: 40% → 60%) e o',
        '    relatório do dia mostra essa evolução',
        '',
        'Mantido do fluxo anterior: busca fuzzy hierárquica de tarefa,',
        '  situação (Executado/Parcial/Não executado), motivo + detalhe,',
        '  lançamentos em sequência sem mouse, relatório do dia com',
        '  executado / não executado / deveria estar / porquês, impressão.',
        '',
        'Obs: estrutura pensada para evoluir — o formato do relatório',
        '  ainda vai ser amadurecido junto com o módulo Relatórios.',
      ]
    },
    {
      versao: 'V2.11.1',
      status: 'fechada',
      data: '2026-07-09',
      tipo: 'correcao',
      titulo: 'Correção: Diário de Obra travava em "Carregando..."',
      itens: [
        'BUG: diario.html chamava Semanal.init() (resquício de quando',
        '  o Diário era aba do Semanal) em vez de Diario.init() —',
        '  Semanal nem é carregado nessa página, então o módulo',
        '  quebrava e a tela ficava travada em "Carregando..." pra sempre',
        'CORRIGIDO: chamada trocada para Diario.init()',
        'Menu lateral: rótulo alterado de "Diário" para "Diário de Obra"',
        '  em todas as 20 páginas do sistema',
      ]
    },
    {
      versao: 'V2.12.0',
      status: 'fechada',
      data: '2026-07-09',
      tipo: 'funcionalidade',
      titulo: '% em família no Planejamento (pai ↔ filhos)',
      itens: [
        'NOVO: porcentagem de conclusão agora trabalha em família,',
        '  estilo MS Project — caminho de mão dupla:',
        '  • Lançou % numa FOLHA → o % do pai (e avós) é recalculado',
        '    automaticamente como média dos filhos ponderada pela',
        '    quantidade (se todos os filhos diretos têm quantidade;',
        '    senão, média simples)',
        '  • Lançou % num PAI → o valor é distribuído para todos os',
        '    descendentes (toast informa quantas tarefas foram afetadas)',
        'Vale nos 3 pontos de lançamento: Planejamento (edição inline',
        '  e modal), Semanal e Diário de Obra — lógica única e',
        '  compartilhada em Utils (percFamilia, recalcularPercAncestrais,',
        '  distribuirPercDescendentes), sem duplicação',
        'Hierarquia lida por ordem + nível, igual ao restante do sistema',
      ]
    },
    {
      versao: 'V2.13.0',
      status: 'fechada',
      data: '2026-07-09',
      tipo: 'funcionalidade',
      titulo: 'Diário de Obra: Pauta do Dia',
      itens: [
        'NOVO: ao abrir o Diário, a pauta da reunião já vem montada —',
        '  tarefas-folha previstas para o dia no Planejamento',
        '  (início <= dia <= término, % < 100), agrupadas pelo pai,',
        '  com % e quantidade/unidade de cada uma. Nada fixo no código:',
        '  a pauta é 100% dirigida pelos dados do Planejamento da obra.',
        'Cards com 3 ações rápidas: ✅ Andou (lança % novo, com prévia',
        '  ao vivo da produção física — delta% × quantidade, na unidade',
        '  da tarefa — e do novo % do pai), ✖ Parado (motivo + detalhe)',
        '  e ⏭ Pular. Tarefa já tratada mostra o badge do lançamento.',
        'Lançamento no PAI (botão "Lançar no grupo" no cabeçalho):',
        '  distribui o % para todas as subtarefas (% em família da V2.12.0)',
        'Seção recolhível de ATRASADAS: término já passou e não concluiu',
        'Tarefas AVULSAS (fora do planejamento, ex: falar com projetista):',
        '  rolam automaticamente para os dias seguintes até serem',
        '  concluídas, e saem como pendências no relatório',
        'Relatório do dia ganhou PRODUÇÃO FÍSICA: totais agrupados por',
        '  unidade (m², m³, un...) + detalhe por tarefa, e bloco de',
        '  pendências avulsas em aberto',
        'Formulário antigo virou "Fora da pauta" (recolhível), com a',
        '  mesma busca fuzzy em todo o Planejamento',
        'Gravação de avanço unificada em caminho único (_gravarAvanco):',
        '  regras de início/término real + % em família',
      ]
    },
    {
      versao: 'V2.13.1',
      status: 'fechada',
      data: '2026-07-09',
      tipo: 'melhoria',
      titulo: 'Pauta do Dia: ajustes de uso em campo',
      itens: [
        'Cards mostram só o NOME da tarefa (sem o código) — o código',
        '  aparece como tooltip ao passar o mouse no nome',
        'Grupos da pauta agora são RECOLHÍVEIS: clique no cabeçalho',
        '  para abrir/fechar e ver os filhos; contador de tratadas',
        '  por grupo (ex: 2/5 tratadas) direto no cabeçalho',
        'ATRASADAS: ordenadas pela ordem do planejamento e agrupadas',
        '  por família (todas as alvenarias juntas, etc.), com o nome',
        '  do pai como divisor',
        'NOVO: busca "Adicionar tarefa do planejamento à pauta" —',
        '  fuzzy pelo nome, adiciona à pauta tarefas do planejamento',
        '  que não estavam previstas para o dia (adiantadas, etc.).',
        '  Avulsas continuam sendo só o que está FORA do planejamento.',
        'Tooltips em todos os botões (Andou, Parado, ⏭ Pular,',
        '  Lançar no grupo, navegação de dias, avulsas...)',
      ]
    },
    {
      versao: 'V2.14.0',
      status: 'fechada',
      data: '2026-07-10',
      tipo: 'correcao',
      titulo: 'Planejamento: 7 correções críticas de usabilidade',
      itens: [
        '1. COLUNA #: número fixo por ordem real da tarefa, não muda',
        '   ao filtrar/recolher famílias. Predecessoras agora buscam por',
        '   esse número (igual MS Project) — digitar "3TI" vincula à',
        '   tarefa de linha 3 do planejamento, não ao código "3".',
        '',
        '2. PREDECESSORAS: agora funcionam de verdade. Ao salvar o campo',
        '   "Predecessora" com o número da linha (ex: "5TI" ou "12TI+2"),',
        '   o início/fim da tarefa é recalculado automaticamente.',
        '',
        '3. TOGGLE ▼/▶: área de clique aumentada (20×20px com fundo',
        '   visível) — muito mais fácil de acertar no celular/tablet.',
        '',
        '4. SCROLL AO TOGGLEAR: abrir/fechar uma família não salta mais',
        '   para o topo — a posição do scroll é preservada.',
        '',
        '5. RESIZE DE COLUNA: área de arraste aumentada de 4px para 10px',
        '   (com margem negativa para facilitar pegar a borda)',
        '   e cursor col-resize visível com dica ao passar o mouse.',
        '',
        '6. CTRL+Z: desfaz a última ação (edição de célula, reordenação).',
        '   Guarda os últimos 30 estados. Funciona no teclado enquanto',
        '   não há nenhum campo de texto ativo.',
        '',
        '7. EDIÇÃO DE CÉLULA: _paintRows() (virtual scroll) não destrói',
        '   mais o input aberto ao rolar a tela. Enquanto há um campo',
        '   em edição, só o Gantt é repintado; a tabela esquerda fica',
        '   intacta até o usuário confirmar (Enter/Tab) ou cancelar (Esc).',
        '',
        'BÔNUS: barra de seleção ganha botões ↑ Acima / ↓ Abaixo',
        '   para mover a tarefa selecionada uma posição (alternativa',
        '   visual ao Ctrl+BotãoDireito+Arrastar).',
      ]
    },
    {
      versao: 'V2.14.1',
      status: 'fechada',
      data: '2026-07-10',
      tipo: 'funcionalidade',
      titulo: 'Mão de Obra e Materiais: vínculo múltiplo + unidades livres',
      itens: [
        'Botão renomeado: "+ Vincular à Tarefa" agora é',
        '  "+ Adicionar Nova Mão de Obra" (módulo Mão de Obra)',
        'VÍNCULO A VÁRIAS TAREFAS DE UMA VEZ: ao adicionar uma mão de',
        '  obra ou material novo, agora dá pra selecionar mais de uma',
        '  tarefa na busca — cada clique adiciona/remove da lista',
        '  (chips abaixo da busca, com "✕" para remover individualmente)',
        '  → Salva um vínculo para cada tarefa selecionada, com o mesmo',
        '    valor/unidade/consumo. Vínculos já existentes são',
        '    ignorados silenciosamente (evita duplicidade)',
        '  → Ao EDITAR um vínculo já existente, a seleção continua',
        '    única (o vínculo representa uma tarefa só)',
        'Válido nos dois módulos: Mão de Obra e Materiais',
        '',
        'UNIDADES DE MEDIÇÃO LIVRES: os campos de unidade que antes',
        '  eram <select> fechado (limitado à lista pré-definida) agora',
        '  aceitam digitação livre, com sugestões da lista existente',
        '  — resolve o caso de unidades faltando, como m³',
        '  → Mão de Obra: "Unidade do valor"',
        '  → Materiais: unidade base do material (biblioteca e ao',
        '    criar novo), unidade de embalagem, unidade base da',
        '    embalagem, unidade de consumo (previsto/real)',
        '  → m³ e combinações com m³ (kg/m³, L/m³, etc.) adicionadas',
        '    como sugestões prontas na lista',
      ]
    },
    {
      versao: 'V2.14.1',
      status: 'fechada',
      data: '2026-07-10',
      tipo: 'correcao',
      titulo: 'Coluna Tarefa redimensionável + predecessoras seguem vínculo ao reordenar',
      itens: [
        'COLUNA "TAREFA" REDIMENSIONÁVEL:',
        '  A coluna de nome da tarefa era do tipo flex:1 (ocupa o espaço',
        '  que sobra), o que impedia o resize por arrasto. Agora:',
        '  → Handle de arrasto visível no cabeçalho da coluna Tarefa',
        '  → Ao arrastar, muda para largura fixa em pixels (gravada em',
        '    colLarguras) — se não foi redimensionada, continua flex:1',
        '  → Atualizado nos 4 lugares: live, PNG header, PNG rows',
        '',
        'PREDECESSORAS SEGUEM O VÍNCULO AO REORDENAR:',
        '  Ao mover uma tarefa (↑ Acima, ↓ Abaixo, ou Ctrl+drag),',
        '  o número # de todas as tarefas que mudaram de posição é',
        '  recalculado. O sistema então varre todas as predecessoras',
        '  e atualiza automaticamente qualquer referência numérica',
        '  que tenha mudado.',
        '  → Exemplo: Concreto era #3, Alvenaria tinha "3TI".',
        '    Após mover Concreto para #4, Alvenaria passa a "4TI".',
        '  → Formatos suportados: "3", "3TI", "3TI+2", "3TT-1" etc.',
        '  → Só atualiza referências que realmente mudaram de número.',
        '  → Toast confirma quantas predecessoras foram atualizadas.',
        '  → Salvamento no Firestore em background.',
      ]
    },
    {
      versao: 'V2.15.0',
      status: 'fechada',
      data: '2026-07-10',
      tipo: 'funcionalidade',
      titulo: 'Módulo Obras vira o hub central de navegação',
      itens: [
        'Tela inicial pós-login agora é a seleção de Obra (era Dashboard)',
        'Sidebar reordenada: Obras aparece antes de Dashboard',
        'Config. da Obra sai do menu lateral e vira ícone ⚙️ direto no card da obra',
        'Card de cada obra mostra % executada (calculada do Planejamento, ponderada por duração das tarefas-folha)',
        'Card de cada obra mostra Início Real (menor inicioReal das tarefas) e Fim Provável (maior terminoPlanejado)',
        'Progresso de cada obra carrega em paralelo e atualiza o card assim que pronto, sem travar a listagem',
      ]
    },
    {
      versao: 'V2.14.2',
      status: 'fechada',
      data: '2026-07-10',
      tipo: 'correcao',
      titulo: 'Coluna Tarefa realmente redimensionável + mover múltiplas linhas',
      itens: [
        'COLUNA TAREFA — resize corrigido de verdade:',
        '  Havia 2 bugs: (1) o header de "nome" entrava num branch',
        '  COL_FIXED que gerava um div sem data-hcol e sem handle;',
        '  (2) o resize live (durante o arrasto) atualizava só o',
        '  data-hcol do header mas as células usam flex:1 e ignoram',
        '  width inline. Correções:',
        '  → Header de "nome" agora tem data-hcol e handle de 10px',
        '  → Células da coluna nome têm data-col="nome"',
        '  → _colResizeStart atualiza header + todas as células',
        '    visíveis por data-col em tempo real, removendo flex',
        '',
        'MOVER MÚLTIPLAS LINHAS:',
        '  Os botões ↑ Acima e ↓ Abaixo agora funcionam com',
        '  1 ou mais tarefas selecionadas ao mesmo tempo.',
        '  → Mover para cima: cada linha selecionada sobe uma posição',
        '    em relação à linha não-selecionada imediatamente acima',
        '    (linhas selecionadas contíguas sobem juntas como bloco)',
        '  → Mover para baixo: idem, descendo',
        '  → Predecessoras remapeadas automaticamente após o movimento',
        '  → Testado: bloco de 2 linhas sobe/desce junto, para no topo',
        '    corretamente quando já está na primeira posição',
      ]
    },
    {
      versao: 'V2.16.0',
      status: 'fechada',
      data: '2026-07-11',
      tipo: 'funcionalidade',
      titulo: 'Módulo Concreto: Levantamento + Controle',
      itens: [
        'Novos módulos "Levantamento de Concreto" e "Controle de Concreto",',
        '  integrados a partir do dashboard de concreto (antes em planilha',
        '  Google Sheets + Apps Script separados) para dentro do sistema',
        '  principal, com todos os dados agora no Firestore da obra.',
        '',
        'LEVANTAMENTO DE CONCRETO (aba Levantamentos):',
        '  → Calculadora de volumes com diagramas: Pilar (retangular,',
        '    redondo, L, T), Rampa e Escada (laje inclinada + patamares',
        '    + degraus), envio direto para a base de peças',
        '  → Base de peças com busca, filtro por andar/tipo e edição',
        '  → Importação em lote (colar do Excel ou carregar TSV/CSV),',
        '    com normalização automática de nomes de andar e modelo',
        '    de planilha para download',
        '  → Montagem de Concretagens em 4 passos: dados → vínculo de',
        '    peças com % (bloqueia peças já 100% alocadas em outra',
        '    concretagem) → configuração das BTs previstas → resumo',
        '  → Configuração da ordem dos andares (arrastar e soltar)',
        '',
        'CONTROLE DE CONCRETO (aba Controle):',
        '  → 6 KPIs: Volume Total, Previsto (+10%), Real Concretado,',
        '    Executado de Projeto, Faltando e Índice de Perda',
        '  → Alerta de peças com lançamento acima do volume de projeto',
        '  → Lançamento e edição de BTs, com % relativo ao volume da',
        '    peça NESTA concretagem e detecção de excesso considerando',
        '    outras BTs já lançadas',
        '  → Progresso por tipo de peça (acordeão) com detalhe da peça',
        '    e histórico de lançamentos por concretagem',
        '  → Status das BTs por concretagem (previsto × usado, perda/',
        '    sobra de caminhão, perda de cocho)',
        '  → Painel da última BT lançada',
        '  → Exportação CSV de peças por concretagem',
        '  → Aba Relatórios: gráficos donut (execução geral e',
        '    distribuição de perdas), volume por andar (gráfico de',
        '    barras SVG com 4 séries), resumo por tipo e índice',
        '    detalhado por BT',
        '',
        'Regras de negócio preservadas do sistema original:',
        '  → Editar concretagem substitui todos os vínculos e BTs',
        '  → Excluir peça remove seus vínculos com concretagens',
        '  → Editar BT já lançada substitui os lançamentos anteriores',
      ]
    },
    {
      versao: 'V2.17.0',
      status: 'fechada',
      data: '2026-07-11',
      tipo: 'funcionalidade',
      titulo: 'Acesso simplificado + Tutorial guiado',
      itens: [
        'Login: acesso simplificado (usuário "0" / senha "0") traduzido',
        '  internamente para uma credencial real do Firebase Auth,',
        '  pensado para acesso rápido de convidados/gestores',
        'Novo módulo Tutorial: pop-up de boas-vindas no primeiro acesso',
        '  → Tour rápido explicando cada aba do menu lateral (o que é,',
        '    como funciona, se já está ou não em funcionamento)',
        '  → Botão "Pular" a qualquer momento e "Próximo" entre os passos',
        '  → Não abre as telas de fato, só um pop-up sobre a tela de Obras',
        '  → Pode ser revisto a qualquer momento pelo botão "🎓 Tutorial"',
        '    na tela de Obras',
        '  → Preferência salva no navegador (não repete depois da 1ª vez)',
      ]
    },
    {
      versao: 'V2.17.1',
      status: 'fechada',
      data: '2026-07-11',
      tipo: 'melhoria',
      titulo: 'Tutorial: explicações completas por módulo',
      itens: [
        'Cada passo do tutorial ganhou lista detalhada de recursos reais',
        '  do módulo (não mais 1 frase genérica), incluindo:',
        '  → Planejamento: hierarquia, % em família, predecessoras,',
        '    custo material/mão de obra, undo, exportação PNG paginada',
        '  → Levantamentos: detalhe de Fachada, Ar Condicionado e Concreto',
        '  → Controle: detalhe dos 6 KPIs e recursos do Controle de Concreto',
        '  → Semanal, Diário, Medições, Mão de Obra, Materiais e Relatórios',
        '    com os fluxos reais de cada um',
        'Modal do tutorial ampliado (modal-lg) para acomodar o conteúdo',
      ]
    },
    {
      versao: 'V2.17.2',
      status: 'fechada',
      data: '2026-07-11',
      tipo: 'correcao',
      titulo: 'Concreto: navegação corrigida + visão fiel ao dashboard original',
      itens: [
        'NAVEGAÇÃO: removidos os links cruzados nos cabeçalhos de',
        '  Levantamento Concreto e Controle Concreto — cada módulo só',
        '  é acessado pelo seu próprio hub (Levantamentos / Controle),',
        '  sem atalho de um para o outro pelo topo da página',
        '',
        'VISÃO: layout reconstruído para bater com o dashboard original',
        '  (Next.js), recolorido para o Design System Absoluta — mesma',
        '  estrutura, cores novas:',
        '  → FiltroBar: cards clicáveis com dropdown (Andar / Concretagem/',
        '    Andar), como no original, no lugar de <select> simples',
        '  → KPIs: cartão com ícone circular colorido por categoria',
        '    (verde/azul/roxo/vermelho/laranja), igual ao original',
        '  → Launch Bar: banner escuro com selo, título, descrição e',
        '    botão grande "⊕ LANÇAR BT →" (Controle) + atalho para o',
        '    Levantamento — recriando a barra de lançamento do original',
        '  → Última BT: painel com selo "Última BT", número grande,',
        '    grid de 4 itens (Concretagem/Previsto/Executado/Perda ou',
        '    Sobra) e selo "Concluído ✓", como no dashboard original',
        '  → Painéis (Progresso por Tipo, Status das BTs, Relatórios)',
        '    convertidos para o componente de painel do original',
        '  → Tabelas e badges (Levantamento e Controle) convertidos',
        '    para o estilo de tabela/badge do dashboard original',
        '  → Wizard de Concretagem: indicador de passos com círculos',
        '    numerados, igual ao original (era um conjunto de pílulas)',
        '  → Cards de seleção (tipo de peça, menu de concretagem)',
        '    convertidos para o "menuCard" do original',
      ]
    },
    {
      versao: 'V2.17.3',
      status: 'fechada',
      data: '2026-07-11',
      tipo: 'correcao',
      titulo: 'Mão de Obra/Materiais: tarefas sem código, vínculo somado em uma linha, correção de bug ao selecionar tarefa',
      itens: [
        'TAREFAS SEM CÓDIGO: a busca/árvore de tarefas (Mão de Obra,',
        '  Materiais e Diário) agora mostra só o nome do serviço/tarefa,',
        '  sem o código na frente (helper compartilhado',
        '  Utils.opcoesTarefaHierarquia)',
        '',
        'VÍNCULO A VÁRIAS TAREFAS = UMA LINHA SÓ: selecionar mais de uma',
        '  tarefa não cria mais uma linha por tarefa — agora gera UM',
        '  único vínculo com todas as tarefas somadas: nomes unidos',
        '  ("Tarefa A + Tarefa B") e quantidade somada (base do cálculo',
        '  do custo total). Vale para Mão de Obra e Materiais.',
        '  → Editar um vínculo existente também permite adicionar ou',
        '    remover tarefas dele (antes só uma tarefa era permitida',
        '    na edição)',
        '  → Planejamento (colunas Custo Material/Custo M.Obra) já lê',
        '    o novo formato — cada tarefa recebe valor×sua própria',
        '    quantidade, mesmo quando o vínculo cobre várias tarefas',
        '  → Vínculos antigos (uma tarefa só) continuam funcionando',
        '    normalmente, sem precisar recriar nada',
        '',
        'CORREÇÃO DE BUG: selecionar uma tarefa na busca não apaga mais',
        '  o que já tinha sido digitado (nome, valor, categoria,',
        '  observações...) — antes o clique recarregava o modal inteiro',
        '  e perdia tudo. Agora só a lista de resultados e os',
        '  "chips" de tarefas selecionadas são atualizados.',
      ]
    },
    {
      versao: 'V2.17.4',
      status: 'fechada',
      data: '2026-07-11',
      tipo: 'correcao',
      titulo: 'Controle: hub do Concreto não estava sendo exibido',
      itens: [
        'BUG: a aba Controle continuava mostrando "Módulo em',
        '  desenvolvimento" mesmo depois do hub com o card Controle',
        '  Concreto ter sido implementado — o controle.html ainda',
        '  chamava Utils.initPagina() direto no carregamento, em vez',
        '  de Controle.init() (que é quem de fato desenha o hub)',
        '  → Corrigido: controle.html agora inicializa via',
        '    Controle.init(), igual às demais páginas do sistema',
        '  → Card "🪨 Controle Concreto" volta a aparecer normalmente',
        '    ao entrar em Controle',
      ]
    },
    {
      versao: 'V2.17.5',
      status: 'fechada',
      data: '2026-07-12',
      tipo: 'funcionalidade',
      titulo: 'Levantamento de Fachada: clonar peças entre balancins',
      itens: [
        'Novo botão "⧉" na árvore, ao lado do lápis, em cada',
        '  balancim — clona as peças de outro balancim (já',
        '  levantado) para dentro do balancim atual',
        'O nome do balancim atual não muda; apenas as peças',
        '  (Vista Externa + Vista Interna) são copiadas com os',
        '  mesmos valores, mas passam a pertencer a este balancim',
        'Se o balancim atual já tiver peças, o sistema avisa e',
        '  substitui pelas peças clonadas (evita duplicidade)',
        'CORREÇÃO: LF.editarNomeInline (renomear na árvore) estava',
        '  faltando no export do módulo — o botão de lápis na',
        '  árvore não funcionava (erro "LF.editarNomeInline is not',
        '  a function"); corrigido, e agora busca o nome atual',
        '  internamente ao invés de depender do onclick',
      ]
    },
    {
      versao: 'V2.17.6',
      status: 'fechada',
      data: '2026-07-12',
      tipo: 'funcionalidade',
      titulo: 'Levantamento de Fachada: coluna "ML?" no relatório de peças',
      itens: [
        'Nova coluna "ML?" na tabela de peças da Vista, com um',
        '  check clicável — mostra se a peça está sendo tratada',
        '  como Metro Linear e permite alternar direto ali',
        'No formulário de Nova Peça, o campo "Pode ser considerado',
        '  Metro Linear" agora é pré-marcado automaticamente com',
        '  base na Configuração de Cálculo (peça com área menor ou',
        '  igual ao limite definido já nasce marcada como ML)',
        'A checkbox continua sendo um double-check manual: se o',
        '  usuário clicar nela, a sugestão automática para de',
        '  sobrescrever aquela peça (respeita a escolha manual)',
        'Ao editar uma peça já existente, o valor salvo é mantido',
        '  como está (não recalcula sozinho por cima do que já foi',
        '  decidido antes)',
      ]
    },
    {
      versao: 'V2.17.7',
      status: 'fechada',
      data: '2026-07-12',
      tipo: 'correcao',
      titulo: 'Levantamento de Fachada: Vão Fechado zerado + coluna m² unitário',
      itens: [
        'BUG: o card "M² Vão Fechado" no topo da tela de Vista',
        '  sempre mostrava 0,00, mesmo com vão(s) cadastrado(s)',
        '  para aquela vista — a função de soma não estava',
        '  recebendo a vista ao calcular o total; corrigido',
        'BUG: exportar CSV (geral ou da vista) quebrava com erro,',
        '  pois tentava usar um campo "vão" que não existia mais',
        '  no cálculo por peça; corrigido',
        'Coluna "Vão F." por peça removida da tabela (não fazia',
        '  sentido — vão fechado é por vista, não por peça)',
        'Nova coluna "m² unit." no lugar: mostra o m² de UMA peça',
        '  só, sem multiplicar pela quantidade (a coluna "m² sem',
        '  ML" continua mostrando o total já multiplicado)',
      ]
    },
    {
      versao: 'V2.17.8',
      status: 'fechada',
      data: '2026-07-12',
      tipo: 'melhoria',
      titulo: 'Levantamento de Fachada: ordem alfabética, cards de vista clicáveis e histórico de acabamento',
      itens: [
        'Peças da tabela da Vista agora aparecem em ordem',
        '  alfabética (antes era pela ordem de cadastro)',
        'Nos cards "Vista Externa" / "Vista Interna" (dentro do',
        '  balancim), o card inteiro agora é clicável — antes só',
        '  o corpo abaixo do título respondia ao clique, e clicar',
        '  em cima do título/ícone não abria a vista',
        'Campo "Acabamento" no formulário de peça agora sugere',
        '  (autocomplete) os acabamentos já usados em outras',
        '  peças da obra, mas continua aceitando texto livre',
        '  digitado na hora',
      ]
    },
    {
      versao: 'V2.17.9',
      status: 'fechada',
      data: '2026-07-12',
      tipo: 'funcionalidade',
      titulo: 'Levantamento de Fachada: contas dentro dos campos de medida (cm)',
      itens: [
        'Agora dá pra digitar uma conta direto nos campos',
        '  Comprimento, Altura, Largura Janela e Altura Janela',
        '  da peça — ex: "291+100" e apertar Enter vira "391"',
        'Aceita +, -, * e / (e parênteses); se não tiver operador',
        '  ou o texto não for uma conta válida, o campo fica',
        '  como o usuário digitou, sem mexer em nada',
      ]
    },
    {
      versao: 'V2.17.10',
      status: 'fechada',
      data: '2026-07-12',
      tipo: 'correcao',
      titulo: 'Levantamento de Fachada: contas também no Vão Fechado',
      itens: [
        'Os campos Comp (cm) e Alt (cm) do modal de Vão Fechado',
        '  agora também aceitam conta (ex: "291+100" + Enter =',
        '  "391"), igual ao formulário de peça',
        'CORREÇÃO: o preview de m² do Vão Fechado estava quebrado',
        '  — o oninput dos campos chamava uma função global que',
        '  não existia (_atualizarPreviewVao em vez de',
        '  LF._atualizarPreviewVao), gerando erro no console',
        '  toda vez que o usuário digitava; corrigido',
      ]
    },
    {
      versao: 'V2.17.11',
      status: 'fechada',
      data: '2026-07-12',
      tipo: 'correcao',
      titulo: 'Levantamento de Fachada: clonar balancim não puxava Vão Fechado nem contava peças na fachada',
      itens: [
        'BUG: ao clonar peças de outro balancim (⧉), o Vão Fechado',
        '  das vistas de origem não era copiado para as vistas do',
        '  balancim de destino; agora é copiado junto',
        'BUG: as peças clonadas ficavam com o fachadaId da',
        '  fachada de ORIGEM em vez da fachada de DESTINO — por',
        '  isso o contador de peças na árvore, ao lado do nome da',
        '  fachada, não batia com a realidade quando se clonava',
        '  entre balancins de fachadas diferentes; corrigido',
        'IMPORTANTE: clones feitos ANTES desta correção continuam',
        '  com o fachadaId errado no banco — se algum balancim',
        '  clonado estiver com contagem estranha, refaça o clone',
        '  (⧉) nele para corrigir os dados',
      ]
    },
    {
      versao: 'V2.17.12',
      status: 'fechada',
      data: '2026-07-12',
      tipo: 'funcionalidade',
      titulo: 'Levantamento de Fachada: botão de corrigir vínculos antigos + breakdown de ML na Visão Geral',
      itens: [
        'Novo botão "🔧" ao lado de "+ Fachada" na Estrutura —',
        '  revisa TODAS as peças e vistas da obra de uma vez e',
        '  corrige o vínculo com a fachada certa (baseado no',
        '  balancim de cada uma). Resolve de vez os clones feitos',
        '  antes da V2.17.11 sem precisar refazer um por um',
        'Nos cards da Visão Geral (mapa), "M² COM ML" agora mostra',
        '  o valor separado: Xm² + YML, com "= Zm²" embaixo — igual',
        '  já aparecia nas outras telas do sistema',
      ]
    },
    {
      versao: 'V2.17.13',
      status: 'fechada',
      data: '2026-07-12',
      tipo: 'funcionalidade',
      titulo: 'Levantamento de Fachada: friso (arquitetônico/estrutural) + fachada não reconhecia clone (raiz do problema)',
      itens: [
        'CORREÇÃO DEFINITIVA: os totais de peças/m²/vão por fachada',
        '  (árvore, Resumo Geral, tela da Fachada, Visão Geral)',
        '  dependiam do campo fachadaId gravado em cada peça/vista',
        '  — se esse campo ficasse desatualizado (ex: em clones),',
        '  a fachada "não reconhecia" as peças mesmo elas estando',
        '  no balancim certo. Agora os totais são calculados pelo',
        '  balancim (fonte da verdade), não mais pelo fachadaId',
        '  solto — o problema de "Fachada Frontal Esquerda" não',
        '  bater com a "Direita" clonada está resolvido de raiz,',
        '  mesmo sem precisar rodar o botão 🔧 de correção',
        'Novo seletor "Possui friso?" na peça (igual ao de janela):',
        '  Comprimento do friso (cm, aceita conta), Tipo',
        '  (Arquitetônico ou Estrutural) e Qtd de frisos',
        'Todo o levantamento agora soma o ML de friso separado',
        '  por tipo — "Friso Arquitetônico" e "Friso Estrutural"',
        '  aparecem no resumo (m² sem ML / com ML / vão) de toda',
        '  vista, balancim, fachada e no total geral, e também nos',
        '  cards da Visão Geral (mapa) e no CSV exportado',
        'Nova coluna "Friso" na tabela de peças, mostrando',
        '  comprimento e tipo (Arq/Est) quando a peça tiver friso',
      ]
    },
    {
      versao: 'V2.17.14',
      status: 'fechada',
      data: '2026-07-12',
      tipo: 'melhoria',
      titulo: 'Levantamento de Fachada: múltiplos frisos por peça',
      itens: [
        '"Possui friso?" agora permite adicionar MAIS DE UM friso',
        '  na mesma peça (igual à lista de Vão Fechado) — botão',
        '  "+ Friso" adiciona linha, cada uma com seu próprio',
        '  Comprimento, Tipo (Arquitetônico/Estrutural) e Qtd',
        'Os totais de ML Friso Arquitetônico/Estrutural agora',
        '  somam todos os frisos de todas as peças corretamente',
        'Coluna "Friso" na tabela mostra o primeiro friso e um',
        '  "+N" quando a peça tem mais de um; passe o mouse em',
        '  cima pra ver a lista completa',
        'Peças com friso cadastrado no formato antigo (um só)',
        '  continuam funcionando normalmente',
      ]
    },
    {
      versao: 'V2.17.15',
      status: 'aberta',
      data: '2026-07-12',
      tipo: 'funcionalidade',
      titulo: 'Levantamento de Fachada: mover peça entre Vista Externa/Interna',
      itens: [
        'Novo botão "⇄" na tabela de peças da Vista — move a peça',
        '  direto pra outra vista do mesmo balancim (Externa ↔',
        '  Interna), sem precisar excluir e recadastrar tudo',
        'Útil pra quando a peça foi lançada na vista errada por',
        '  engano',
      ]
    }
  ],

  render(containerId) {
    const c = document.getElementById(containerId);
    if (!c) return;
    const icon = { lancamento:'🚀', correcao:'🔧', funcionalidade:'✨', melhoria:'📈' };
    const stLabel = { aberta:'Em aberto', fechada:'Fechada' };
    c.innerHTML = `
      <div class="page-header">
        <div>
          <h2>📋 Notas de Versão</h2>
          <span class="subtitulo">Versão atual: <strong>${this.versaoAtual}</strong></span>
        </div>
      </div>
      <div style="display:flex;flex-direction:column;gap:14px;">
        ${this.versoes.slice().reverse().map(v => `
          <div style="background:#fff;border-radius:10px;border:1.5px solid ${v.status==='aberta'?'var(--cor-primaria)':'var(--cor-borda-light)'};overflow:hidden;">
            <div style="background:${v.status==='aberta'?'var(--cor-primaria)':'var(--cor-dark-800)'};padding:13px 20px;display:flex;align-items:center;gap:10px;">
              <span style="font-size:1.2rem;">${icon[v.tipo]||'📌'}</span>
              <div style="flex:1">
                <div style="font-weight:800;color:${v.status==='aberta'?'#000':'#fff'};">${v.versao} — ${v.titulo}</div>
                <div style="font-size:.75rem;color:${v.status==='aberta'?'rgba(0,0,0,.55)':'#777'};margin-top:2px;">${new Date(v.data).toLocaleDateString('pt-BR')}</div>
              </div>
              <span style="padding:2px 10px;border-radius:100px;font-size:.7rem;font-weight:700;background:${v.status==='aberta'?'rgba(0,0,0,.12)':'rgba(255,255,255,.08)'};color:${v.status==='aberta'?'#000':'#aaa'};">${stLabel[v.status]}</span>
            </div>
            <ul style="list-style:none;padding:14px 20px;display:flex;flex-direction:column;gap:5px;margin:0;">
              ${v.itens.map(item => {
                const sub = item.startsWith('  →');
                const text = item.replace(/^  →\s*/,'');
                return `<li style="display:flex;gap:8px;font-size:${sub?.8:.855}rem;color:${sub?'#888':'var(--cor-texto)'};padding-left:${sub?14:0}px;">
                  <span style="margin-top:3px;color:${sub?'#bbb':'var(--cor-primaria-dark)'};font-size:.65rem;flex-shrink:0;">${sub?'↳':'▸'}</span>${text}</li>`;
              }).join('')}
            </ul>
          </div>`).join('')}
      </div>`;
  }
};
