// Notas de Versão — atualizado a cada commit
const NotasVersao = {
  versaoAtual: 'V2.2.4',

  versoes: [
    {
      versao: 'V1.0',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'lancamento',
      titulo: 'Lançamento Oficial da Base',
      itens: [
        'Sistema publicado em produção (Vercel + Firebase)',
        'Identidade visual Absoluta: preto + amarelo #F5C800',
        'Logo oficial, sidebar escura, header com borda amarela',
        'Card especial obra Essence/Zenith com foto',
        'Módulo Obras: criar, listar, editar, excluir',
        'Módulo Configuração da Obra: etapas, pacotes, locais, equipes',
        'Módulo Levantamentos (hub)',
        'Módulo Levantamento de Fachada — calculadora completa',
        '  → Hierarquia: Fachada → Balancim → Vista → Peça',
        '  → m² sem ML, m² com ML, Metro Linear, Vão Fechado',
        '  → Checkbox "Pode ser ML" por peça',
        '  → 4 modos de desconto de janela configuráveis',
        '  → Vão fechado por Vista (não por peça)',
        '  → Visão Geral com mapa PNG + caixas posicionáveis',
        '  → Exportação CSV',
        'Módulo Planejamento V1: Gantt, Linha de Balanço, Escadinha, Tabela',
        'Auditoria automática em todas as operações',
      ]
    },
    {
      versao: 'V1.0.1',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'correcao',
      titulo: 'Correções de autenticação e dados',
      itens: [
        'firebase-config.js: reutiliza app existente (não chama initializeApp duas vezes)',
        'Fachada: carregar com fallback duplo (sem orderBy → com createdAt)',
        'Fachada: múltiplas fachadas abertas na árvore simultaneamente',
        'Fachada: ✎ inline para renomear fachada/balancim',
        'Fachada: Visão Geral antes do Resumo Geral',
        'Fachada: canvas branco com padding para posicionamento',
        'Fachada: card de total geral na Visão Geral',
        'Obras: editar obra existente funcionando',
        'Router: troca de obra recarrega módulo automaticamente',
        'Notas de Versão: criadas e acessíveis na sidebar',
      ]
    },
    {
      versao: 'V1.0.2',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'correcao',
      titulo: 'Correção definitiva de autenticação',
      itens: [
        'auth.js: reescrito do zero — sem timers conflitantes',
        '  → onAuthStateChanged ignora null completamente (Firebase restaurando sessão)',
        '  → Timeout único de 8s só ativa se realmente não houver sessão',
        '  → Resolve definitivamente o bug de usuário sumindo ao navegar',
        'utils.js: initPagina sem timeout próprio — usa apenas o do auth',
        '  → Erros do Firestore (seletor de obras) não bloqueiam a página',
        '  → Usuário nunca é redirecionado por erro de Firestore',
        'Versão atual visível na sidebar (ex: V1.0.2)',
        'Notas de versão bumpeadas a cada commit (V1.0.2)',
        'CRÍTICO fachada: cxVincular não existia → travava o módulo inteiro',
        '  → Corrigido para cxEditar e salvarCxEdit',
        '  → LevantamentoFachada undefined era consequência deste erro',
        'Obras: removidas imagens hardcoded (Essence/Zenith)',
        'Obras: botão Inserir Imagem no modal — cada obra tem sua própria foto',
        'Fachada: toggle Visão Geral agora abre primeiro (antes de Resumo Geral)',
        'Fachada: mapa migra dados de chave antiga (fachadaMap_null) para chave correta',
        '  → Imagem importada volta a aparecer após correção do bug anterior',
        'Mapa (Visão Geral): migrado de localStorage para Firestore',
        '  → Imagem e posições das caixas disponíveis em qualquer dispositivo',
        '  → Carregado junto com os dados da fachada no init()',
        'Layout geral: sidebar fixa em 100vh, usuário sempre visível sem scroll',
        'Visão Geral: layout compacto — topbar, total e mapa cabem na tela',
        '  → Toggle + botões na mesma linha (topbar)',
        '  → Mapa ocupa o espaço restante da tela automaticamente',
        '  → Imagem responsiva dentro da área de mapa',
        'Imagens: migradas de base64/localStorage para Firebase Storage',
        '  → Mapa da Visão Geral: upload para Storage, URL salva no Firestore',
        '  → Imagem de capa das obras: upload para Storage',
        '  → Resolve limite de 1MB do Firestore e persistência entre dispositivos',
        'Mapa: imagem no tamanho natural com scroll — não mais cortada',
        'Imagem: compressão via canvas (sem Firebase Storage) — sem loading infinito',
        '  → Reduz para <900KB antes de salvar no Firestore',
        '  → Qualidade progressiva: 85% → 30% até caber',
        'Visão Geral: sidebar esquerda oculta para maximizar área do mapa',
        '  → Aparece de volta ao entrar no Resumo Geral',
        'Visão Geral: imagem ocupa toda a largura disponível (fit)',
        'Drag das caixas: reescrito com mouse events (mousedown/mousemove/mouseup)',
        '  → Movimento preciso, sem travar, sem voltar ao lugar inicial',
        '  → Considera scroll do wrapper no cálculo de posição',
      ]
    },
    {
      versao: 'V1.0.3',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'correcao',
      titulo: 'Correções de layout e mapa',
      itens: [
        'Imagem do mapa: compressão via canvas — sem loading infinito',
        'Imagem do mapa: salva comprimida no Firestore (sem Firebase Storage)',
        'Visão Geral: sidebar esquerda oculta para maximizar área do mapa',
        'Visão Geral: imagem ocupa toda a largura disponível (fit)',
        'Drag das caixas: reescrito com mousedown/mousemove/mouseup',
        '  → Movimento preciso, não volta ao lugar inicial',
        '  → Considera scroll do wrapper no cálculo de posição',
        'Layout geral: sidebar fixa em 100vh, usuário sempre visível',
        'Versão atualizada para V1.0.3 em todos os arquivos',
      ]
    },
    {
      versao: 'V1.0.4',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'correcao',
      titulo: 'Visão Geral: sidebar, drag e imagem corrigidos',
      itens: [
        'Sidebar esquerda oculta na Visão Geral — toda a tela para o mapa',
        '  → Grade muda para 1 coluna (sem sidebar)',
        '  → Volta ao normal no Resumo Geral',
        'Drag das caixas reescrito corretamente com mouse events',
        '  → Caixas se movem livremente, não travam, não voltam ao lugar',
        '  → Offset calculado relativo ao mapa-area com scroll do wrapper',
        'Ícone de cadeado: 🔓 aberto (livre) / 🔒 fechado (travado) — visível',
        'Botões da caixa não ativam drag ao clicar (stopPropagation)',
        'Imagem ocupa 100% da largura do mapa com scroll quando maior',
        'pointer-events:none no container, pointer-events:all por caixa',
      ]
    }
    ,{
      versao: 'V1.0.5',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'correcao',
      titulo: 'Sidebar, caixas livres e imagem fit',
      itens: [
        'Sidebar da estrutura: id adicionado ao HTML — agora some de verdade na Visão Geral',
        'Caixas sem limite de posição — movem livremente para qualquer lugar',
        'Imagem do mapa: object-fit contain — cabe na tela sem scroll, sem corte',
        'Save do mapa: log de debug + validação de tamanho antes de salvar',
        '  → Mostra erro claro se imagem ainda for grande demais',
      ]
    },
    {
      versao: 'V1.0.6',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'correcao',
      titulo: 'Estrutura some + zoom do mapa',
      itens: [
        'Coluna Estrutura (fachada-tree): agora some de verdade na Visão Geral',
        '  → renderPainel() usa getElementById corretamente',
        '  → Volta ao abrir Resumo Geral',
        'Controles de zoom na Visão Geral: − / % / + / ↺ reset',
        '  → Zoom de 20% a 300% para ajustar a imagem na tela',
        '  → Caixas escalam junto com a imagem',
        'Mapa: overflow auto — scroll só quando zoom > tela',
      ]
    },
    {
      versao: 'V1.0.7',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'correcao',
      titulo: 'Canvas infinito + redimensionar imagem',
      itens: [
        'Botão ✎ Tamanho na topbar — abre slider para ajustar largura da imagem',
        '  → Slider de 200px a 3000px em tempo real',
        '  → Caixas permanecem onde estão ao redimensionar',
        'Canvas infinito (2000×1400px mínimo) com fundo pontilhado',
        '  → Caixas podem ficar em qualquer lugar, inclusive fora da imagem',
        '  → Scroll livre para navegar pelo canvas',
        'Imagem posicionada no canto superior esquerdo do canvas',
        '  → Margem de 40px ao redor para posicionar caixas fora da imagem',
      ]
    },
        {
      versao: 'V1.0.8',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'correcao',
      titulo: 'Imagem arrastável e redimensionável com handles',
      itens: [
        'Imagem do mapa: drag para mover (arrastar em qualquer direção)',
        'Imagem do mapa: 8 handles amarelos nos cantos e bordas para redimensionar',
        '  → Arrastar canto: resize proporcional',
        '  → Arrastar borda: resize direcional',
        'Imagem cabe na tela ao importar (fit automático)',
        'Canvas sem overflow/scroll — imagem e caixas sempre visíveis',
        'Borda tracejada amarela indica que a imagem é editável',
      ]
    },
    {
      versao: 'V1.0.9',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'correcao',
      titulo: 'Resize correto, fundo branco, caixas livres, cadeado legível',
      itens: [
        'Handles de resize: corrigidos — agora redimensiona a imagem corretamente',
        'Caixas: drag corrigido — posição relativa ao canvas (não à area)',
        'Fundo do canvas: branco puro (sem pontinhos)',
        'Cadeado: substituído por texto LIVRE (verde) / TRAV (vermelho)',
        '  → Muito mais legível que emoji de cadeado',
      ]
    },
    {
      versao: 'V1.1.0',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'funcionalidade',
      titulo: 'Resize completo de imagem e caixas na Visão Geral',
      itens: [
        'Imagem: 8 handles amarelos para redimensionar (4 cantos + 4 bordas)',
        '  → Cantos: resize proporcional (mantém proporção da imagem)',
        '  → Bordas E/W: estica horizontalmente',
        '  → Bordas N/S: estica verticalmente com proporção',
        'Imagem: arrastar para mover livremente no canvas',
        'Imagem: fit automático ao importar (cabe na tela)',
        'Caixas: handle ⤡ no canto inferior direito para redimensionar largura',
        '  → Conteúdo se adapta à largura da caixa',
        'Caixas: ficam sempre em cima da imagem (z-index:20 vs z-index:1)',
        'Canvas: fundo branco puro, sem pontinhos',
        'Lock: LIVRE (verde) / TRAV (vermelho) — legível',
      ]
    },
    {
      versao: 'V1.1.1',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'correcao',
      titulo: 'Visão Geral: modo edição, imgState no Firestore, resize caixas',
      itens: [
        'Imagem: botão Editar Imagem ativa modo edição (borda amarela)',
        'Imagem: botão Confirmar salva posição/tamanho no Firestore e trava',
        '  → Imagem não se move/redimensiona fora do modo edição',
        'Imagem: imgState (x,y,w) salvo no Firestore — persiste ao recarregar',
        'Caixas: resize em largura (E) e altura (S) separados',
        '  → Handle ⤡ no canto: resize em diagonal (largura+altura)',
        '  → Barra na base: resize só em altura',
        'Caixas: ficam acima da imagem (z-index:30 vs z-index:1)',
      ]
    },
    {
      versao: 'V1.1.2',
      status: 'fechada',
      data: '2025-07-04',
      tipo: 'correcao',
      titulo: 'Caixas nunca cortadas + imgState persistido',
      itens: [
        'Caixas: movidas para overlay fora do canvas (overflow:visible)',
        '  → Nunca mais cortadas — podem ir para qualquer lugar da tela',
        'imgState salvo no Firestore — posição e tamanho da imagem persistem',
        'Modo edição: botão confirmar salva e trava imagem',
        'Resize caixas: handle ⤡ para largura+altura simultâneos',
        'Texto das caixas: flex-wrap para refluir ao redimensionar',
      ]
    },
    {
      versao: 'V1.1.3',
      status: 'fechada',
      data: '2025-07-05',
      tipo: 'correcao',
      titulo: 'Auth corrigido, fórmula ML do config, vãos múltiplos',
      itens: [
        'CRÍTICO: carregar() agora carrega mapaVisao do Firestore novamente',
        '  → Imagem e caixas voltam ao abrir a página',
        '  → Usuário não buga mais ao entrar em fachada',
        'Fórmula ML: usa ml_percentual do config (não mais fixo em 50%)',
        '  → Ex: 100% → ml conta inteiro no equivalente: 6m² + 4ml = 10m²',
        '  → Ex: 50%  → ml conta metade: 6m² + 4ml = 8m²',
        'Vão Fechado por Vista: múltiplos vãos por vista',
        '  → Cada vão tem Comprimento, Altura e Quantidade',
        '  → Botão + Adicionar Vão para incluir mais vãos',
        '  → Total acumulado exibido em tempo real',
      ]
    },
    {
      versao: 'V1.1.4',
      status: 'fechada',
      data: '2025-07-05',
      tipo: 'correcao',
      titulo: 'CRÍTICO: funções perdidas restauradas',
      itens: [
        'CAUSA RAIZ do bug: reescritas da Visão Geral deletaram funções essenciais',
        '  → importarMapa, cxAdicionar, cxRemover, cxTravar, cxEditar, salvarCxEdit, limparMapa',
        '  → return{} exportava funções inexistentes → IIFE falhava → módulo undefined',
        '  → Usuário bugava porque o módulo não carregava',
        'Todas as funções restauradas e verificadas (47 exportadas, todas existem)',
        'cxTravar e cxEditar agora rerenderizam só as caixas (sem reload do painel inteiro)',
      ]
    },
    {
      versao: 'V1.1.5',
      status: 'fechada',
      data: '2025-07-05',
      tipo: 'correcao',
      titulo: 'Drag das caixas: reescrito simples e direto',
      itens: [
        'cxMouseDown: usa delta (startX/startY) em vez de getBoundingClientRect do overlay',
        '  → Não depende do overlay existir ou ter posição correta',
        '  → Move exatamente o quanto o mouse se deslocou',
        '  → Salva posição final no Firestore ao soltar',
      ]
    },
    {
      versao: 'V1.1.6',
      status: 'fechada',
      data: '2025-07-05',
      tipo: 'correcao',
      titulo: 'Drag caixas: header é a alça de arrasto',
      itens: [
        'CAUSA RAIZ do drag não funcionar:',
        '  → onmousedown estava no div pai, mas header tinha stopPropagation',
        '  → Qualquer clique passava pelo header e cancelava o evento',
        'Fix: onmousedown movido para o HEADER (barra amarela)',
        '  → Arrastar pelo header amarelo move a caixa',
        '  → Botões ainda têm stopPropagation para não arrastar ao clicar',
      ]
    },
    {
      versao: 'V1.2',
      status: 'fechada',
      data: '2025-07-05',
      tipo: 'funcionalidade',
      titulo: 'Planejamento funcional + Módulo Materiais',
      itens: [
        'PLANEJAMENTO — Importar Excel:',
        '  → Aceita .xlsx e .xls (SheetJS via CDN, sem instalação)',
        '  → Detecta colunas em PT e EN automaticamente',
        '  → Importa: Código, Nome, Tipo, Datas, Duração, %, Responsável, Etapa, Pacote, Local',
        '  → Calcula duração automaticamente se tiver datas',
        '  → Trata datas em DD/MM/YYYY, YYYY-MM-DD e serial Excel',
        'PLANEJAMENTO — Exportar Excel:',
        '  → Gera .xlsx com todas as tarefas',
        '  → Inclui aba de Instruções de importação',
        '  → Nome do arquivo inclui obra e data',
        'PLANEJAMENTO — Gantt melhorado:',
        '  → Linha Hoje em amarelo com label',
        '  → Barra executada real (início/término real)',
        '  → Zoom dia/semana/mês/trimestre/ano',
        'MATERIAIS — Novo módulo:',
        '  → Vínculo com tarefas do Planejamento',
        '  → Vínculo com Fachadas do Levantamento',
        '  → Consumo Previsto × Quantidade da tarefa = total calculado',
        '  → Detalhes da tarefa/fachada ao filtrar',
        '  → CRUD completo com tipo, fabricante, unidade',
      ]
    },
    {
      versao: 'V1.2.1',
      status: 'fechada',
      data: '2025-07-05',
      tipo: 'correcao',
      titulo: 'Correções Planejamento e Materiais',
      itens: [
        'Planejamento: Router.getObraAtiva → Router.getObra (exportar funcionando)',
        'Materiais: removido stub de desenvolvimento',
        'Materiais: modal de cadastro adicionado ao HTML',
        'Materiais: Levantamento Fachada aparece como UMA entrada agregada',
        '  → Agrupa todas as fachadas com m² total e detalhe por fachada',
        '  → Não lista cada fachada separada',
        'Materiais: layout organizado com tabela e filtros no topo',
      ]
    },
    {
      versao: 'V1.2.2',
      status: 'fechada',
      data: '2025-07-05',
      tipo: 'funcionalidade',
      titulo: 'Materiais: biblioteca + vínculos por UID',
      itens: [
        'Estrutura em duas coleções separadas:',
        '  → materiais/ = biblioteca (cada material com UID único)',
        '  → materiais_vinculos/ = vínculo materialId + tarefaId + consumo',
        'Aba Biblioteca: cadastrar materiais com nome, tipo, fabricante, referência',
        '  → Ex: Cimento CP-III Votorantim e Cimento CP-III Cauê são IDs diferentes',
        '  → Coluna mostra em quantas tarefas cada material é usado',
        'Aba Por Tarefa: vincular material da biblioteca a uma tarefa/serviço',
        '  → Busca material pelo nome na biblioteca (não digitação manual)',
        '  → Consumo Previsto × Quantidade da tarefa = total calculado',
        '  → Avisa duplicidade (mesmo material + mesma tarefa)',
        '  → Link rápido para cadastrar na biblioteca se não encontrar',
      ]
    },
    {
      versao: 'V1.2.3',
      status: 'fechada',
      data: '2025-07-05',
      tipo: 'correcao',
      titulo: 'Materiais polido + Excel sem conflito',
      itens: [
        'Excel exportar: colunas sem acentos (Inicio, Termino, Nivel, Perc Concluido)',
        '  → Importar detecta com ou sem acento, normaliza automaticamente',
        'Materiais: botão ← Por Tarefa na tela de Biblioteca',
        'Materiais: modal único Vincular / Criar com toggle no topo',
        '  → Vincular: busca na biblioteca',
        '  → Criar: formulário inline, salva na biblioteca e vincula de uma vez',
        'Unidade de consumo: sempre no formato X/Y (kg/m², L/m², un/un...)',
        '  → Consumo real herda a mesma unidade (label dinâmico)',
        '  → Dropdown com opções padrão de mercado',
        'Card de tarefa: exibe apenas total (m², un...) sem listar fachadas',
      ]
    },
    {
      versao: 'V1.2.4',
      status: 'fechada',
      data: '2025-07-05',
      tipo: 'correcao',
      titulo: 'Materiais: editar corrigido, embalagem, relatório por balancim',
      itens: [
        'Editar material na biblioteca: botão funcionando (preenchimento manual)',
        'Material com conversão de embalagem: 1 saco = 20 kg',
        '  → Total exibido em unidade base E em embalagem',
        '  → Ex: 840 kg = 42 sacos de 20 kg',
        'Relatório Fachada: ao filtrar por [Levantamento] Fachada',
        '  → Tabela por material com breakdown por Fachada e por Balancim',
        '  → Total por fachada e total geral em destaque amarelo',
        '  → Mostra total em unidade base e em embalagem se configurado',
        'HTML do modal reconstruído limpo (sem duplicação)',
        'Consumo real: label dinâmico com mesma unidade do previsto',
      ]
    },
    {
      versao: 'V1.2.5',
      status: 'fechada',
      data: '2025-07-05',
      tipo: 'correcao',
      titulo: 'Importar/Exportar Excel: formato exato do modelo',
      itens: [
        'IMPORTAR: detecta colunas do modelo real (ID, Código, Nome, Duração...)',
        '  → Colunas: ID, Código, Nome, Duração, Início, Término, % Esperado',
        '  → % Concluído, Prececessora, Tarefa Pai, Grupo, Local, Custo, Receita',
        '  → Responsável, Inicio/Termino Linha de Base, Inicio/Termino Desafio',
        '  → Duração no formato Xd (ex: 20d)',
        '  → Datas no formato DD/MM/YYYY',
        '  → Hierarquia detectada por recuo de espaços no nome',
        'IMPORTAR: gravação em lotes de 50 (sem loading infinito)',
        '  → Antes: 2399 awaits sequenciais = travava',
        '  → Agora: Promise.all em lotes = rápido',
        'EXPORTAR: cabeçalho idêntico ao modelo importável',
        '  → Nome com recuo por nível (2 espaços por nível)',
        '  → Datas em DD/MM/YYYY, duração com sufixo d',
        '  → Todas as 19 colunas do modelo',
      ]
    },
    {
      versao: 'V1.3',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'funcionalidade',
      titulo: 'Planejamento: Gantt tipo MS Project',
      itens: [
        'Hierarquia: grupos com ▼/▶ para recolher/expandir filhos',
        'Hierarquia: botões ← → na tabela para recuar/avançar nível',
        'Hierarquia: Ctrl++ nova tarefa, Ctrl+- excluir selecionada',
        'Colunas: botão ⚙ Colunas para mostrar/esconder cada coluna',
        'Divisor: barra amarela entre tabela e Gantt é arrastável',
        'Scroll sincronizado: esquerda e direita rolam juntos',
        'Importar: confirma antes de substituir, apaga antigas primeiro',
        'Exportar Gantt: botão 🖼 Gantt PDF gera imagem PNG',
        'Zoom: dia/semana/mês/trimestre/ano com escala correta',
        'Modal tarefa: todos os campos do modelo Excel',
        'Barras de grupo: formato chapéu (MS Project style)',
        'Linha de base e desafio como campos separados',
      ]
    },
    {
      versao: 'V1.3.1',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'correcao',
      titulo: 'Planejamento: performance + duplicatas + colunas',
      itens: [
        'PERFORMANCE: renderização virtual — só linhas visíveis no viewport',
        '  → 2400 tarefas sem travar (antes renderizava tudo de uma vez)',
        '  → Scroll sincronizado esquerda/direita',
        'Coluna # (número da linha) sempre visível',
        'Coluna Predecessora visível',
        'Esconder coluna: clique no ▼ no header da própria coluna',
        '  → Botão "Mostrar colunas" aparece quando alguma está oculta',
        'Import: evita duplicatas (chave código+nome)',
        '  → Limpa tudo antes de importar',
        'Inserir tarefa: herda nível/grupo da selecionada, empurra as demais',
        'Ctrl++ insere, Ctrl+- exclui selecionada',
        'Divisor amarelo arrastável entre tabela e Gantt',
      ]
    },
    {
      versao: 'V1.3.2',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'correcao',
      titulo: 'Planejamento: colunas, import, hierarquia, zoom',
      itens: [
        'Colunas: nomes completos (Duração, % Esperado, % Concluído, Predecessora)',
        'Colunas: clique DIREITO no header para esconder (menos sensível)',
        'Colunas: mostrar individual — popup lista apenas as ocultas',
        'Colunas: arrastar borda direita do header para redimensionar largura',
        'Import: removida deduplicação — todas as linhas são importadas',
        '  → Suporte a 10.000+ linhas (lotes de 200)',
        '  → Linhas com mesmo nome mas níveis diferentes são mantidas',
        'Hierarquia ← →: move a tarefa E todos os filhos abaixo dela',
        '  → Igual MS Project: outdent/indent puxa a família inteira',
        'Zoom: escala correta dia/semana/mês/trimestre/ano',
      ]
    },
    {
      versao: 'V1.3.3',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'correcao',
      titulo: 'Planejamento: ← → no Gantt, zoom correto, esconder Gantt',
      itens: [
        'Aba Tabela removida — tudo feito pelo Gantt',
        'Botões ← → de hierarquia agora no Gantt (coluna Ações)',
        '  → Recuar/avançar move tarefa + todos os filhos abaixo',
        'Botão Esconder Gantt: esconde as barras e deixa só a tabela',
        '  → Toggle: clica de novo para mostrar o Gantt',
        'Zoom headers corrigidos:',
        '  → Dia: mostra cada dia individualmente',
        '  → Semana: linhas verticais por semana com número do dia',
        '  → Mês: label por mês com ano',
        '  → Trimestre: T1/T2/T3/T4 com ano',
        '  → Ano: só o número do ano',
        'Coluna Ações alargada (64px) para caber ← → ✎',
      ]
    },
    {
      versao: 'V2.0',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'funcionalidade',
      titulo: 'Planejamento V2.0 — reescrita completa',
      itens: [
        'EDIÇÃO INLINE: clique na célula para editar direto (sem modal)',
        '  → Enter salva, Escape cancela, Tab avança',
        '  → Funciona para todos os campos editáveis',
        'COLUNA NÍVEL: mostra o nível hierárquico de cada tarefa',
        'HIERARQUIA ← →: move tarefa + todos os filhos abaixo',
        '  → Update em paralelo para performance',
        '  → Atualiza dados locais antes de recarregar',
        'COLUNAS:',
        '  → Nomes completos sem abreviação',
        '  → Clique DIREITO no header para esconder',
        '  → Mostrar: popup lista ocultas individualmente',
        '  → Arrastar borda direita do header para redimensionar',
        '  → Arrastar header para reordenar (drag and drop)',
        '  → Reorder não afeta importar/exportar Excel',
        'TOGGLE GANTT: 1 clique para esconder/mostrar',
        '  → Tabela ocupa tela toda quando Gantt oculto',
        '  → Não reaparece ao scrollar',
        'ZOOM CORRETO:',
        '  → Dia: cada dia individualmente',
        '  → Semana: linhas por semana',
        '  → Mês: label por mês',
        '  → Trimestre: T1/T2/T3/T4',
        '  → Ano: só número do ano',
        'EXPORTAR PNG: gera imagem completa do Gantt',
        '  → Expande temporariamente para capturar tudo',
        'IMPORT: sem deduplicação, lotes de 200, limpa antes',
        'PERFORMANCE: virtual scroll + requestAnimationFrame',
      ]
    },
    {
      versao: 'V2.0.1',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'correcao',
      titulo: 'Gantt corrigido, hierarquia funcional, nível por código',
      itens: [
        'Gantt: barras voltaram — linha Hoje usa getElementById (não querySelector)',
        '  → querySelector encontrava barras de grupo e corrompia o HTML',
        'Hierarquia ← →: atualiza dados LOCALMENTE primeiro (sem esperar Firestore)',
        '  → Feedback visual imediato ao clicar',
        '  → Salva no Firestore em background em lotes de 20',
        '  → Mostra erro se tarefa já está no nível mínimo (0)',
        'Nível importado pelo CÓDIGO: 1=nível 0, 1.1=nível 1, 1.1.1=nível 2',
        '  → Antes usava espaços no nome (impreciso)',
        '  → Agora conta pontos no código = nível',
      ]
    },
    {
      versao: 'V2.0.2',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'correcao',
      titulo: 'Gantt restaurado, hierarquia por nível, famílias',
      itens: [
        'GANTT BARRAS: corrigido width:440% → width:440px no painel esquerdo',
        '  → Painel esquerdo ocupava 440% da tela, empurrando Gantt pra fora',
        'FAMÍLIAS por nível: ▼/▶ funciona baseado no NÍVEL hierárquico',
        '  → Recolher grupo esconde tudo abaixo com nível maior',
        '  → Detecta filhos pela próxima tarefa na ordem ter nível maior',
        '  → Não depende mais do campo tarefaPai',
        'NÍVEL NO IMPORT: conta pontos no código (1.3.1.1 = nível 3)',
        '  → PRECISA REIMPORTAR o Excel para corrigir os níveis',
        '← → HIERARQUIA: atualiza local primeiro (resposta imediata)',
        '  → Salva no Firestore em background',
      ]
    },
    {
      versao: 'V2.0.3',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'correcao',
      titulo: 'Divisor livre, nível por spinner, datas automáticas, predecessora',
      itens: [
        'DIVISOR: arrasta de 60px até quase o final da tela (sem limite rígido)',
        'NÍVEL: spinner funciona — change event dispara save automaticamente',
        '  → Ao mudar nível, filhos são movidos junto (MS Project)',
        'DATAS AUTOMÁTICAS (3 modos):',
        '  → Início + Fim → calcula Duração',
        '  → Início + Duração → calcula Fim',
        '  → Predecessora → calcula Início e Fim',
        'PREDECESSORA tipo MS Project:',
        '  → Formato: código + tipo (ex: 3TI, 1.2II, 5TT)',
        '  → TI = Término-Início (default): começa após a predecessora',
        '  → II = Início-Início: começa junto com a predecessora',
        '  → TT = Término-Término: termina junto com a predecessora',
        '  → Defasagem: 3TI+2 = 2 dias após término da tarefa 3',
        'RESIZE COLUNAS: arrasta borda direita do header',
      ]
    },
    {
      versao: 'V2.0.4',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'correcao',
      titulo: 'Colunas resize/reorder, predecessora popup, esconder coluna',
      itens: [
        'RESIZE COLUNAS: handle visível (amarelo ao hover) na borda direita do header',
        '  → Arrasta para redimensionar, cursor muda para col-resize',
        '  → Re-renderiza ao soltar para consistência',
        'REORDENAR COLUNAS: drag and drop nos headers',
        '  → Borda amarela indica onde vai cair',
        '  → Não afeta exportar/importar Excel',
        'ESCONDER COLUNA: clique direito no header (restaurado)',
        '  → Botão + Colunas aparece quando há ocultas',
        'PREDECESSORA — duplo clique abre popup:',
        '  → Campo de código com preview da tarefa em tempo real',
        '  → Seletor TI/II/TT/IT com descrição',
        '  → Campo de defasagem em dias',
        '  → Mostra nome, datas da predecessora',
        '  → Botão Limpar para remover predecessora',
        'PREDECESSORA — clique simples: edita o código inline',
      ]
    },
    {
      versao: 'V2.0.5',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'correcao',
      titulo: 'Resize/reorder colunas corrigidos, predecessora popup, PNG intervalo',
      itens: [
        'RESIZE COLUNAS: overlay invisível durante arrasto (sem conflito com drag)',
        '  → Desativa draggable dos headers enquanto resize',
        '  → Cursor col-resize no corpo inteiro durante arrasto',
        'REORDENAR COLUNAS: drag & drop com dataTransfer',
        '  → Coluna arrastada fica translúcida',
        '  → Borda amarela no destino',
        '  → Funciona com todas as colunas não-fixas',
        'PREDECESSORA: clique abre popup direto (sem inline)',
        '  → Código azul sublinhado indica que é clicável',
        '  → Popup com preview, tipo TI/II/TT/IT, defasagem',
        'PNG: popup pede intervalo (início/fim)',
        '  → Datas pré-preenchidas com período do projeto',
        '  → Gera PNG completo no intervalo selecionado',
      ]
    },
    {
      versao: 'V2.0.6',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'correcao',
      titulo: 'Resize colunas, reordenar, predecessora, PNG corrigidos',
      itens: [
        'RESIZE COLUNAS: overlay + linha guia amarela',
        '  → Removido HTML5 drag API (conflitava com resize)',
        '  → Handle na borda direita fica amarelo ao hover',
        '  → Overlay captura mouse, linha guia mostra posição',
        'REORDENAR COLUNAS: via menu (clique direito no header)',
        '  → Opções: ◀ Mover esquerda, Mover direita ▶, ✕ Esconder',
        '  → Removido drag&drop que não funcionava',
        'PREDECESSORA: console.log adicionado para debug',
        '  → Clique abre popup com preview em tempo real',
        'PNG: scale reduzido para 1x e altura limitada a 8000px',
        '  → Evita arquivo corrompido por canvas muito grande',
      ]
    },
    {
      versao: 'V2.0.7',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'correcao',
      titulo: 'CRÍTICO: funções faltando no return corrigidas',
      itens: [
        'insertTarefa removido (alias duplicado de inserirTarefa)',
        '_hideCol adicionada como função standalone',
        '  → Estava referenciada no menu mas não definida',
        '  → IIFE falhava → módulo undefined → usuário bugava',
        'Verificação: todas as 30 funções do return confirmadas',
      ]
    },
    {
      versao: 'V2.0.8',
      status: 'fechada',
      data: '2025-07-06',
      tipo: 'correcao',
      titulo: 'Divisor independente, resize colunas, PNG confiável',
      itens: [
        'DIVISOR: tabela tem min-width fixo e overflow:hidden',
        '  → Arrastar o divisor CORTA a tabela (não encolhe colunas)',
        '  → Colunas mantêm largura original, conteúdo é clipado',
        'RESIZE COLUNAS: handle de 8px com borda amarela visível ao hover',
        '  → Posição right:-3px para facilitar o clique',
        '  → stopPropagation evita conflito com outros eventos',
        'PNG: captura a tela como está (sem expandir)',
        '  → Usa toBlob em vez de toDataURL (mais confiável)',
        '  → Scale 2x para qualidade boa',
        '  → Sem expandir container (evita canvas gigante corrompido)',
        '30/30 funções do return verificadas',
      ]
    },
    {
      versao: 'V2.0.9',
      status: 'fechada',
      data: '2025-07-07',
      tipo: 'correcao',
      titulo: 'CRÍTICO: _totalColWidth não definida quebrava o módulo',
      itens: [
        '_totalColWidth era chamada no render mas nunca foi definida',
        '  → ReferenceError quebrava todo o Planejamento',
        'Função adicionada: soma larguras das colunas visíveis',
        'Verificação ampliada: return{} + TODAS as funções chamadas no código',
        '  → 30 funções do return OK, 29 funções internas OK',
      ]
    },
    {
      versao: 'V2.1.0',
      status: 'fechada',
      data: '2025-07-07',
      tipo: 'funcionalidade',
      titulo: 'Módulo Relatórios: "Relatórios de Vista" com IA',
      itens: [
        'Novo módulo Relatórios implementado (antes stub)',
        'Importa PDF de nota (Samsung Notes, digitada ou manuscrita)',
        '  → Nova Vercel Function api/gerar-relatorio.js chama a IA (Claude)',
        '  → Lê o PDF diretamente (sem OCR separado) e devolve JSON estruturado',
        '  → Chave de API fica só no servidor (ANTHROPIC_API_KEY no Vercel)',
        'Relatório salvo no Firestore: obras/{obraId}/relatorios',
        'PDF original arquivado no Firebase Storage',
        'Tela "Relatórios de Vista": lista os últimos relatórios em cards',
        'Visualização formatada: título, resumo, seções, pendências',
        'Botão Baixar: gera novo PDF formatado (jsPDF) e também arquiva no Storage',
        'Botão Compartilhar: abre WhatsApp com texto + link do PDF gerado',
        'Botão Excluir: remove do Firestore e do Storage (original + gerado)',
        '10/10 funções do return OK, 8/8 funções internas OK',
      ]
    },
    {
      versao: 'V2.1.1',
      status: 'fechada',
      data: '2025-07-07',
      tipo: 'correcao',
      titulo: 'Relatórios: troca de provedor de IA para API gratuita',
      itens: [
        'api/gerar-relatorio.js migrada de Anthropic (paga) para Google Gemini',
        '  → Camada gratuita da API (sem custo dentro da cota de uso)',
        '  → Variável de ambiente agora é GEMINI_API_KEY (não usa mais ANTHROPIC_API_KEY)',
        '  → Chave gerada sem cartão em aistudio.google.com/apikey',
        'Modelo usado: gemini-2.5-flash, com responseMimeType JSON nativo',
        'Testado manualmente no AI Studio com nota real — aprovado',
        'Layout do PDF de saída (jsPDF) validado com conteúdo real gerado pela IA',
      ]
    },
    {
      versao: 'V2.1.2',
      status: 'fechada',
      data: '2025-07-07',
      tipo: 'correcao',
      titulo: 'CRÍTICO: relatorios.html não chamava Relatorios.init()',
      itens: [
        'relatorios.html chamava Utils.initPagina() direto no DOMContentLoaded',
        '  → Relatorios.init() nunca era executado',
        '  → Tela ficava travada no placeholder estático "Módulo em desenvolvimento"',
        'Corrigido para chamar Relatorios.init(), igual aos demais módulos',
      ]
    },
    {
      versao: 'V2.1.3',
      status: 'fechada',
      data: '2025-07-07',
      tipo: 'funcionalidade',
      titulo: 'Relatórios: fallback automático Gemini → Claude',
      itens: [
        'api/gerar-relatorio.js agora tenta Gemini primeiro (gratuito)',
        '  → Se falhar (erro, timeout, JSON inválido, bug de billing do Google), cai automaticamente para Anthropic (pago, estável)',
        '  → Precisa de GEMINI_API_KEY e ANTHROPIC_API_KEY configuradas no Vercel',
        'Timeout de 25s (Gemini) e 30s (Anthropic) via AbortController',
        'maxDuration da function ampliado para 60s (tenta os dois provedores em sequência se necessário)',
        'Resposta da API agora inclui "provedor" usado (gemini ou anthropic)',
        'relatorios.js: exibe aviso ao usuário quando o fallback pago é usado',
      ]
    },
    {
      versao: 'V2.1.4',
      status: 'fechada',
      data: '2025-07-07',
      tipo: 'correcao',
      titulo: 'Relatórios: link de compartilhar força download do PDF',
      itens: [
        'PDF gerado agora sobe ao Storage com Content-Disposition: attachment',
        '  → Ao abrir o link no WhatsApp, o PDF baixa em vez de só abrir em visualização inline',
        'Mensagem do WhatsApp deixa explícito "📥 Baixar relatório (PDF)" antes do link',
        'Nome do arquivo padronizado (mesmo nome usado no botão Baixar)',
      ]
    },
    {
      versao: 'V2.1.5',
      status: 'fechada',
      data: '2025-07-07',
      tipo: 'funcionalidade',
      titulo: 'Relatórios: compartilhar envia o PDF anexado de verdade (no celular)',
      itens: [
        'compartilharWhatsapp agora tenta Web Share API (navigator.share) com o PDF como File',
        '  → No celular, abre o menu nativo de compartilhar com o arquivo já anexado',
        '  → Escolhendo WhatsApp, o PDF vai anexado de verdade, não como link',
        'Cancelamento do usuário no menu nativo (AbortError) não gera erro/toast',
        'Fallback mantido: desktop ou navegador sem suporte usa o link via wa.me como antes',
        'PDF sempre salvo no Storage independente do método (link de backup)',
      ]
    },
    {
      versao: 'V2.1.6',
      status: 'fechada',
      data: '2025-07-07',
      tipo: 'correcao',
      titulo: 'Relatórios: nome do arquivo baixado/compartilhado padronizado',
      itens: [
        'Formato: "Nome da Obra - Planejamento e Andamento - Data do relatório.pdf"',
        '  → Ex: "Residencial Essence - Planejamento e Andamento - 17-07-2025.pdf"',
        'Usa a data extraída pela IA (dataRelatorio) quando disponível, senão a data de criação',
        'Sanitização de caracteres inválidos em nome de arquivo (\\ / : * ? " < > |)',
        'Mesmo nome usado no botão Baixar, no Compartilhar (share nativo) e no fallback de link',
      ]
    },
    {
      versao: 'V2.2.0',
      status: 'fechada',
      data: '2025-07-07',
      tipo: 'funcionalidade',
      titulo: 'Relatórios: compartilhamento direto do Samsung Notes (PWA) + aba Pendentes',
      itens: [
        'ATENÇÃO: Relatórios migraram de subcoleção por obra (obras/{obraId}/relatorios)',
        '  para coleção raiz "relatorios" com campo obraId — relatórios de teste antigos',
        '  criados antes desta versão não aparecem mais (não foram migrados)',
        'database.js: novos helpers genéricos para coleções de nível raiz',
        '  (listarRaiz, obterRaiz, criarRaiz, atualizarRaiz, deletarRaiz, queryRaiz, novoIdRaiz)',
        'manifest.json novo: site agora é instalável como PWA, com share_target',
        '  → aceita receber arquivo PDF compartilhado por outros apps (Samsung Notes)',
        'service-worker.js novo: intercepta o POST do compartilhamento, guarda o PDF',
        '  temporariamente no IndexedDB e redireciona para share-target.html',
        'share-target.html + js/share-target.js novos: recebem o PDF, chamam a IA',
        '  (mesmo endpoint /api/gerar-relatorio) e salvam como relatório PENDENTE (obraId: null)',
        'vercel.json novo: rewrite de /share-target/ para /share-target.html',
        'Ícones do PWA gerados a partir do logo existente (icons/icon-192.png, icon-512.png)',
        'utils.js: registra manifest + service worker automaticamente em toda página autenticada',
        'relatorios.js: nova estrutura com abas "Desta Obra" e "Pendentes"',
        '  → Pendentes lista relatórios sem obraId, com dropdown pra atribuir à obra certa',
        '  → Ao atribuir, só atualiza o campo obraId (arquivo já processado, sem reprocessar)',
        'relatorios.html?aba=pendentes abre direto na aba Pendentes (usado pelo botão pós-compartilhamento)',
        '12/12 funções do return OK (relatorios.js), verificado manualmente (comentários no',
        '  return{} do database.js geraram falso positivo no script automático de checagem)',
      ]
    },
    {
      versao: 'V2.2.1',
      status: 'fechada',
      data: '2026-07-07',
      tipo: 'correcao',
      titulo: 'CRÍTICO: drag travado (Pointer Capture) — Planejamento e Fachada',
      itens: [
        'CAUSA RAIZ identificada: arrastar (resize de coluna, divisor, caixas',
        '  da Visão Geral, mover/redimensionar imagem) usava mousemove/mouseup',
        '  no document. Se o botão do mouse era solto FORA da janela do',
        '  navegador (comum com trackpad/monitor externo), o evento de',
        '  soltura nunca chegava — o listener ficava "vivo" para sempre,',
        '  reagindo a qualquer movimento de mouse na página depois.',
        '  Isso explica: caixas da fachada "enlouquecendo", imagem travada',
        '  sem conseguir confirmar posição, e o Planejamento parecendo',
        '  travar/sumir (um overlay invisível de tela cheia ficava preso',
        '  bloqueando cliques em tudo, inclusive a barra lateral).',
        '',
        'CORREÇÃO: todos os arrastos agora usam Pointer Capture',
        '  (setPointerCapture/releasePointerCapture), que garante que o',
        '  evento de soltura SEMPRE chega ao elemento correto, não importa',
        '  onde o mouse for solto. Aplicado em:',
        '  → Planejamento: resize de coluna, divisor tabela/Gantt',
        '  → Fachada: arrastar caixa, redimensionar caixa, arrastar imagem,',
        '    redimensionar imagem',
        'Removido overlay de tela cheia do resize de coluna (não é mais',
        '  necessário — Pointer Capture dispensa essa técnica)',
        'Botões dentro do header das caixas (Travar/Editar/Remover) agora',
        '  bloqueiam a propagação corretamente (estavam usando mousedown',
        '  enquanto o arrasto passou a escutar pointerdown — clique neles',
        '  também iniciava um arrasto por engano)',
      ]
    },
    {
      versao: 'V2.2.2',
      status: 'fechada',
      data: '2026-07-07',
      tipo: 'correcao',
      titulo: 'CRÍTICO: Service Worker com escopo raiz travava troca de módulo',
      itens: [
        'CAUSA RAIZ: o service worker do compartilhamento (Samsung Notes)',
        '  era registrado com escopo raiz ("/"), passando a controlar TODA',
        '  a navegação do site — literalmente toda troca de módulo (cada',
        '  link da sidebar) passava a ser interceptada por ele.',
        '',
        'CORREÇÃO: service worker agora registrado com escopo restrito a',
        '  /share-target/ (única rota que ele realmente precisa controlar,',
        '  usada pelo compartilhamento do Android). A navegação normal',
        '  entre módulos deixa de passar por ele.',
        '',
        'LIMPEZA AUTOMÁTICA: navegadores que já tinham o service worker',
        '  antigo (escopo raiz) registrado de antes desta correção têm',
        '  esse registro antigo removido automaticamente no próximo',
        '  carregamento de qualquer página — não precisa limpar cache',
        '  manualmente.',
      ]
    }
  ],

  render(containerId) {
    const c = document.getElementById(containerId);
    if (!c) return;
    const icon = { lancamento:'🚀', correcao:'🔧', funcionalidade:'✨', melhoria:'📈' };
    const stLabel = { aberta:'Em aberto', fechada:'Fechada' };
    c.innerHTML = `
      <div class="page-header">
        <div>
          <h2>📋 Notas de Versão</h2>
          <span class="subtitulo">Versão atual: <strong>${this.versaoAtual}</strong></span>
        </div>
      </div>
      <div style="display:flex;flex-direction:column;gap:14px;">
        ${this.versoes.slice().reverse().map(v => `
          <div style="background:#fff;border-radius:10px;border:1.5px solid ${v.status==='aberta'?'var(--cor-primaria)':'var(--cor-borda-light)'};overflow:hidden;">
            <div style="background:${v.status==='aberta'?'var(--cor-primaria)':'var(--cor-dark-800)'};padding:13px 20px;display:flex;align-items:center;gap:10px;">
              <span style="font-size:1.2rem;">${icon[v.tipo]||'📌'}</span>
              <div style="flex:1">
                <div style="font-weight:800;color:${v.status==='aberta'?'#000':'#fff'};">${v.versao} — ${v.titulo}</div>
                <div style="font-size:.75rem;color:${v.status==='aberta'?'rgba(0,0,0,.55)':'#777'};margin-top:2px;">${new Date(v.data).toLocaleDateString('pt-BR')}</div>
              </div>
              <span style="padding:2px 10px;border-radius:100px;font-size:.7rem;font-weight:700;background:${v.status==='aberta'?'rgba(0,0,0,.12)':'rgba(255,255,255,.08)'};color:${v.status==='aberta'?'#000':'#aaa'};">${stLabel[v.status]}</span>
            </div>
            <ul style="list-style:none;padding:14px 20px;display:flex;flex-direction:column;gap:5px;margin:0;">
              ${v.itens.map(item => {
                const sub = item.startsWith('  →');
                const text = item.replace(/^  →\s*/,'');
                return `<li style="display:flex;gap:8px;font-size:${sub?.8:.855}rem;color:${sub?'#888':'var(--cor-texto)'};padding-left:${sub?14:0}px;">
                  <span style="margin-top:3px;color:${sub?'#bbb':'var(--cor-primaria-dark)'};font-size:.65rem;flex-shrink:0;">${sub?'↳':'▸'}</span>${text}</li>`;
              }).join('')}
            </ul>
          </div>`).join('')}
      </div>`;
  }
};
